
'use client';

import React from 'react';
import {
  ArrowRight,
  Bot,
  FileUp,
  LayoutTemplate,
  Palette,
  Target,
  Share2,
  Gem,
  Sparkles,
  Gauge,
  Mails,
  Binoculars,
  Video,
  BarChart,
  Repeat,
  CalendarCheck,
  Award,
  Megaphone,
  Zap,
  Users,
  TrendingUp,
  Filter,
  Lightbulb,
  ShieldCheck,
  BrainCircuit,
  ClipboardCheck,
  FileText,
  Clock,
  Briefcase,
  PenTool,
  MessageCircle,
  Mail,
  Calendar,
  DollarSign,
  MapPin,
  ClipboardList,
  FilePlus,
  Network,
  Handshake,
  Headset,
  BookOpen,
  Camera,
  LineChart,
  FileSearch,
  Building,
  Key,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import { LandingHeader } from '@/components/landing-header';
import { LandingFooter } from '@/components/landing-footer';
import { Confetti } from '@/components/confetti';
import { useToast } from '@/hooks/use-toast';

const features = [
  {
    id: 'ad-creation',
    title: 'Instant Ad Creation',
    description: 'Generate high-performance ad copy and visuals from any brochure in seconds.',
    icon: <Megaphone />,
    color: 'from-pink-500/80 to-pink-600/80',
    synergies: {
      'ad-creation': "The Genesis: Spark brilliant campaigns from a single idea.",
      targeting: 'Fine-tune ads with hyper-specific buyer personas.',
      rebranding: 'Ensure every ad matches your new brand identity.',
      'landing-pages': 'Create ads that drive traffic to optimized pages.',
      'social-posts': 'Turn ad concepts into a full social media blitz.',
      'lead-gen': 'A lead is worthless without an ad to capture it.',
      'competitor-analysis': 'Create ads that outperform your biggest rivals.',
      'market-analysis': 'Base your ads on real-time market trends.',
      'auto-follow-up': 'Instantly engage ad respondents with automated sequences.',
      'performance-dashboard': 'Track your ad spend and ROI in one place.',
      'email-campaigns': 'Use ad visuals and copy in your email blasts.',
      'crm-integration': 'Pipe new leads from ads directly into your CRM.',
      'brochure-rebrand': 'Turn any developer brochure into a branded masterpiece.',
      'offer-management': 'Drive ad traffic to a dedicated offer portal.',
      'calendar-sync': 'Let ad leads book meetings directly in your calendar.',
      'bulk-actions': 'Launch a dozen ad variations with a single click.',
      'ai-chatbot': 'Qualify ad leads 24/7 with an AI assistant.',
      'pdf-ads': 'Convert static PDFs into interactive, lead-generating ads.',
      'video-ads': 'Generate compelling video ads that stop the scroll.',
      'content-syndication': 'Push your ad content across a network of platforms.',
      'client-portal': 'Give clients a real-time view of their ad campaigns.',
      'ai-negotiator': 'Let AI handle initial offers from ad leads.',
      'pms-integration': 'Sync ad campaigns with your property management system.',
      'training-modules': 'Learn the secrets of high-converting ad copy.',
      'virtual-tours': 'Embed immersive 3D tours directly into your ads.',
      'roi-calculator': 'Project the potential return of your ad campaigns.',
      'listing-management': 'Create ads for all your listings automatically.',
      'open-house-scheduler': 'Funnel ad traffic to open house sign-up forms.',
      'closing-assistance': 'Generate all necessary closing docs from ad lead data.',
      'predictive-analytics': 'Anticipate which ad creative will perform best.',
      'referral-program': 'Build referral campaigns to amplify your ads.',
      'gamified-sales': 'Create ad campaigns that drive friendly competition.',
      'dynamic-pricing': 'Automatically adjust ad offers based on demand.',
      'a/b-testing': 'Test multiple ad versions to find the winner.',
      'local-seo': 'Boost your ad visibility in local search results.',
      'community-engagement': 'Target community groups with tailored ads.',
      'automated-reporting': 'Send clients beautiful, automated ad performance reports.',
      'script-generator': 'Generate scripts for video ads or sales calls.',
      'drip-campaigns': 'Nurture ad leads with long-term, automated email drips.',
      'task-automation': 'Automatically create follow-up tasks for new ad leads.',
      'feedback-surveys': 'Survey ad respondents to refine your messaging.',
      'real-time-alerts': 'Get instant notifications for new ad leads.',
      'compliance-checker': 'Ensure your ads meet all regulatory standards.',
      'document-generator': 'Generate contracts from ad lead information.',
      'property-websites': 'Create a unique website for each property you advertise.',
      'multi-language': 'Generate ads in multiple languages to reach a wider audience.',
      'voice-search': 'Optimize your ad campaigns for voice search queries.',
      'vr-staging': 'Use virtually staged photos in your property ads.',
      'market-reports': 'Incorporate hyper-local market data into your ads.',
      'agent-collaboration': 'Collaborate with your team on ad campaigns.',
      'commission-tracking': 'Track commissions earned from ad-generated leads.',
      'social-listening': 'Discover new ad angles by listening to social conversations.',
      'chat-integration': 'Engage with ad leads instantly via live chat.',
      'contract-management': 'Manage the entire contract lifecycle from an ad lead.',
      'showing-feedback': 'Collect feedback from showings generated by your ads.',
      'expense-tracking': 'Track every dollar spent on your ad campaigns.',
      'brand-kit': 'Ensure all your ads are perfectly on-brand.',
      'interactive-maps': 'Include interactive maps in your ad landing pages.',
      'event-promotion': 'Promote open houses and other events with targeted ads.',
      'content-calendar': 'Schedule your ad campaigns in a visual calendar.',
      '3d-floor-plans': 'Showcase properties with immersive 3D floor plans in your ads.',
    },
  },
  {
    id: 'targeting',
    title: 'Precision Targeting',
    description: 'Our AI analyzes your project and identifies high-intent buyers.',
    icon: <Target />,
    color: 'from-blue-500/80 to-blue-600/80',
    synergies: {
      'ad-creation': 'Power your ad campaigns with the perfect audience.',
      'targeting': "The Bullseye: Zero in on your most profitable customers.",
      rebranding: 'Rebrand your materials for a specific niche market.',
      'landing-pages': 'Drive high-intent buyers to your landing pages.',
      'social-posts': 'Tailor social content to high-value demographics.',
      'lead-gen': 'Focus your lead generation efforts on the right people.',
      'competitor-analysis': 'Find audiences your competitors are missing.',
      'market-analysis': 'Target buyers based on real-time market shifts.',
      'auto-follow-up': 'Customize follow-up sequences for different buyer segments.',
      'performance-dashboard': 'See which audience segments are most profitable.',
      'email-campaigns': 'Segment your email lists with incredible precision.',
      'crm-integration': 'Enrich your CRM contacts with detailed targeting data.',
      'brochure-rebrand': 'Adapt your brochures to appeal to different buyer personas.',
      'offer-management': 'Send targeted offers to specific buyer groups.',
      'calendar-sync': 'Allow pre-qualified segments to book meetings.',
      'bulk-actions': 'Apply targeting profiles across all your campaigns.',
      'ai-chatbot': 'Use different chatbot personalities for different audiences.',
      'pdf-ads': 'Target PDF ad distribution to specific professional groups.',
      'video-ads': 'Create video ad variations for different target personas.',
      'content-syndication': 'Syndicate content to platforms where your target audience lives.',
      'client-portal': 'Show clients exactly who their marketing is reaching.',
      'ai-negotiator': 'Adjust negotiation tactics based on the buyer profile.',
      'pms-integration': 'Identify potential buyers from your existing tenant database.',
      'training-modules': 'Master the art of psychographic and behavioral targeting.',
      'virtual-tours': 'See which demographics engage most with 3D tours.',
      'roi-calculator': 'Calculate ROI for campaigns targeting different segments.',
      'listing-management': 'Automatically match listings to the ideal buyer profile.',
      'open-house-scheduler': 'Target open house invites to the most likely buyers.',
      'closing-assistance': 'Anticipate the needs of different buyer types during closing.',
      'predictive-analytics': 'Predict which buyer segments will be most valuable.',
      'referral-program': 'Target referral requests to your most satisfied clients.',
      'gamified-sales': 'Create targeting challenges for your sales team.',
      'dynamic-pricing': 'Offer different prices to different buyer segments.',
      'a/b-testing': 'Test which audience responds best to your messaging.',
      'local-seo': 'Dominate local search for your target buyer keywords.',
      'community-engagement': 'Engage with niche communities your buyers belong to.',
      'automated-reporting': 'Generate reports showing the value of precise targeting.',
      'script-generator': 'Create sales scripts tailored to specific buyer personas.',
      'drip-campaigns': 'Develop unique nurture campaigns for each buyer segment.',
      'task-automation': 'Assign high-value leads to your best agents automatically.',
      'feedback-surveys': 'Get feedback from specific buyer personas to refine your strategy.',
      'real-time-alerts': 'Get alerted when a high-value prospect is on your site.',
      'compliance-checker': 'Ensure your targeting practices are fair and compliant.',
      'document-generator': 'Pre-populate documents based on buyer segment data.',
      'property-websites': 'Create different versions of a site for different audiences.',
      'multi-language': 'Target audiences in their native language.',
      'voice-search': 'Optimize for the questions your target audience is asking.',
      'vr-staging': 'See which virtual staging styles appeal to different buyers.',
      'market-reports': 'Provide targeted market reports to specific buyer personas.',
      'agent-collaboration': 'Assign agents to the leads they are best suited for.',
      'commission-tracking': 'Analyze commission data by lead source and target audience.',
      'social-listening': 'Find your target audience by listening to their conversations.',
      'chat-integration': 'Route chats to specialized agents based on user data.',
      'contract-management': 'Use different contract templates for different buyer types.',
      'showing-feedback': 'Analyze showing feedback based on buyer demographics.',
      'expense-tracking': 'Allocate your budget to the most profitable audience segments.',
      'brand-kit': 'Adapt your brand voice for different target audiences.',
      'interactive-maps': 'Highlight different map features for different buyer personas.',
      'event-promotion': 'Promote events to the people most likely to attend.',
      'content-calendar': 'Plan your content around the interests of your target audience.',
      '3d-floor-plans': 'Customize 3D floor plans for different family sizes or lifestyles.',
    },
  },
  {
    id: 'rebranding',
    title: 'Automated Rebranding',
    description: 'Instantly rebrand any brochure with your logo, colors, and voice.',
    icon: <Palette />,
    color: 'from-orange-500/80 to-orange-600/80',
    synergies: {
      'ad-creation': 'Generate on-brand ads in a single click.',
      targeting: 'Adapt your brand voice for different buyer segments.',
      'rebranding': "The Makeover: Instantly apply your brand to any asset.",
      'landing-pages': 'Instantly apply your branding to new landing pages.',
      'social-posts': 'Maintain a consistent brand voice across all social channels.',
      'lead-gen': 'Ensure all your lead capture forms match your brand.',
      'competitor-analysis': 'Differentiate your brand from the competition.',
      'market-analysis': 'Rebrand your materials to match current design trends.',
      'auto-follow-up': 'All your automated emails will be perfectly on-brand.',
      'performance-dashboard': 'Customize your dashboard with your own branding.',
      'email-campaigns': 'Create beautiful, on-brand email templates in seconds.',
      'crm-integration': 'Your brand identity will be consistent across all platforms.',
      'brochure-rebrand': 'The core of your rebranding efforts, made effortless.',
      'offer-management': 'Brand your offer portal to build trust.',
      'calendar-sync': 'Your booking page will reflect your unique brand.',
      'bulk-actions': 'Apply your branding to a hundred listings at once.',
      'ai-chatbot': 'Your chatbot will speak in your brand\'s voice.',
      'pdf-ads': 'Ensure your brand stands out in every PDF.',
      'video-ads': 'Apply your brand kit to video intros and outros automatically.',
      'content-syndication': 'Syndicate perfectly branded content everywhere.',
      'client-portal': 'Offer a white-labeled, branded portal to your clients.',
      'ai-negotiator': 'Your AI negotiator will reflect your brand\'s professionalism.',
      'pms-integration': 'Maintain brand consistency across property management comms.',
      'training-modules': 'Train your team on your brand voice and guidelines.',
      'virtual-tours': 'Add your logo and brand colors to virtual tours.',
      'roi-calculator': 'Present ROI calculations in beautifully branded reports.',
      'listing-management': 'Ensure every listing detail page is on-brand.',
      'open-house-scheduler': 'Brand your open house sign-up pages.',
      'closing-assistance': 'All closing documents will feature your branding.',
      'predictive-analytics': 'Analyze how brand consistency impacts your bottom line.',
      'referral-program': 'Create a branded portal for your referral partners.',
      'gamified-sales': 'Use brand elements in your sales leaderboards.',
      'dynamic-pricing': 'Present pricing and offers with your brand\'s look and feel.',
      'a/b-testing': 'Test different brand messages to see what resonates.',
      'local-seo': 'A consistent brand helps build local search authority.',
      'community-engagement': 'Engage with communities using a consistent brand persona.',
      'automated-reporting': 'All client reports will be perfectly branded.',
      'script-generator': 'Generate scripts that are always in your brand\'s tone of voice.',
      'drip-campaigns': 'Ensure your long-term nurture campaigns are consistently branded.',
      'task-automation': 'Branded templates for all your automated communications.',
      'feedback-surveys': 'Design surveys that match your brand identity.',
      'real-time-alerts': 'Customize alert notifications with your brand colors.',
      'compliance-checker': 'Keep a record of your consistently branded communications.',
      'document-generator': 'Generate beautifully branded documents and contracts.',
      'property-websites': 'Spin up fully branded property websites in minutes.',
      'multi-language': 'Ensure your brand voice is translated correctly.',
      'voice-search': 'Your brand name will be a key part of your voice search strategy.',
      'vr-staging': 'Apply branded virtual furniture to your listings.',
      'market-reports': 'Deliver market reports that reflect your brand\'s expertise.',
      'agent-collaboration': 'Ensure every agent on your team uses the correct branding.',
      'commission-tracking': 'View your earnings in a dashboard styled with your brand.',
      'social-listening': 'Track how your brand is perceived online.',
      'chat-integration': 'Your live chat widget will match your website\'s branding.',
      'contract-management': 'Brand the entire contract experience for your clients.',
      'showing-feedback': 'Collect feedback using your branded survey forms.',
      'expense-tracking': 'Organize your expenses in a branded interface.',
      'brand-kit': 'The central hub for all your automated rebranding efforts.',
      'interactive-maps': 'Customize the style of your interactive maps to match your brand.',
      'event-promotion': 'All event promotion materials will be consistently branded.',
      'content-calendar': 'Visualize your on-brand content schedule.',
      '3d-floor-plans': 'Add your brand watermark to 3D floor plans.',
    },
  },
  {
    id: 'landing-pages',
    title: 'Landing Page Generator',
    description: 'Generate persuasive landing pages that captivate buyers.',
    icon: <LayoutTemplate />,
    color: 'from-green-500/80 to-green-600/80',
    synergies: {
      'ad-creation': 'Create the perfect destination for your ad clicks.',
      targeting: 'Build unique landing pages for each target audience.',
      rebranding: 'Generate a dozen branded landing pages in minutes.',
      'landing-pages': "The Conversion Engine: Build pages that turn clicks into clients.",
      'social-posts': 'Link social posts to high-converting pages.',
      'lead-gen': 'High-converting landing pages are lead-generation machines.',
      'competitor-analysis': 'Build pages that are better than your competitors\'.',
      'market-analysis': 'Update landing page content with real-time market data.',
      'auto-follow-up': 'Trigger follow-up sequences when a lead is captured on a page.',
      'performance-dashboard': 'Track page views, bounce rates, and conversions.',
      'email-campaigns': 'Use landing pages as the destination for your email CTAs.',
      'crm-integration': 'New leads from landing pages flow right into your CRM.',
      'brochure-rebrand': 'Use rebranded assets on your new landing pages.',
      'offer-management': 'Embed your offer portal directly into a landing page.',
      'calendar-sync': 'Allow visitors to book a showing from the landing page.',
      'bulk-actions': 'Create landing pages for all your listings in one go.',
      'ai-chatbot': 'Add a chatbot to your landing pages to engage visitors 24/7.',
      'pdf-ads': 'Create landing pages specifically for your PDF ad campaigns.',
      'video-ads': 'Embed your video ads at the top of your landing pages.',
      'content-syndication': 'Drive syndicated traffic to your targeted landing pages.',
      'client-portal': 'Create unique landing pages for each of your clients.',
      'ai-negotiator': 'Start the negotiation process right from the landing page.',
      'pms-integration': 'Create landing pages for rental listings from your PMS.',
      'training-modules': 'Learn the principles of high-converting landing page design.',
      'virtual-tours': 'Make your virtual tours the centerpiece of your landing pages.',
      'roi-calculator': 'Add an ROI calculator to your landing pages to engage investors.',
      'listing-management': 'Automatically generate a landing page for every new listing.',
      'open-house-scheduler': 'Use landing pages as the sign-up destination for open houses.',
      'closing-assistance': 'Create a secure portal for document exchange during closing.',
      'predictive-analytics': 'Predict which landing page designs will perform best.',
      'referral-program': 'Create a landing page for your referral program sign-ups.',
      'gamified-sales': 'Create contests based on landing page conversion rates.',
      'dynamic-pricing': 'Show personalized pricing on your landing pages.',
      'a/b-testing': 'Test different headlines, images, and CTAs on your landing pages.',
      'local-seo': 'Optimize your landing pages for local search terms.',
      'community-engagement': 'Create landing pages for specific community events or initiatives.',
      'automated-reporting': 'See which landing pages are generating the most leads.',
      'script-generator': 'Generate compelling copy for your landing pages.',
      'drip-campaigns': 'Enroll landing page leads into targeted drip campaigns.',
      'task-automation': 'Automatically create tasks when a landing page form is submitted.',
      'feedback-surveys': 'Add a feedback survey to your landing page thank you page.',
      'real-time-alerts': 'Get an alert the moment a lead is captured on a landing page.',
      'compliance-checker': 'Ensure your landing pages have all necessary disclaimers.',
      'document-generator': 'Allow users to generate sample documents from your landing page.',
      'property-websites': 'A landing page can be a full micro-site for a property.',
      'multi-language': 'Create landing page variations for different languages.',
      'voice-search': 'Optimize landing page content for question-based voice queries.',
      'vr-staging': 'Showcase virtually staged properties on your landing pages.',
      'market-reports': 'Offer a detailed market report as a lead magnet on your pages.',
      'agent-collaboration': 'Collaborate with your team on landing page design and copy.',
      'commission-tracking': 'Track which landing pages lead to the highest commissions.',
      'social-listening': 'Get landing page copy ideas from social media conversations.',
      'chat-integration': 'Add live chat to your landing pages to answer questions instantly.',
      'contract-management': 'Start the contract process from a secure landing page.',
      'showing-feedback': 'Drive users to a feedback form after they visit a landing page.',
      'expense-tracking': 'Track the cost vs. revenue of your landing page campaigns.',
      'brand-kit': 'Ensure your landing pages are always perfectly on-brand.',
      'interactive-maps': 'Embed interactive neighborhood maps on your landing pages.',
      'event-promotion': 'Create dedicated landing pages for each of your events.',
      'content-calendar': 'Schedule when your new landing pages will go live.',
      '3d-floor-plans': 'Feature interactive 3D floor plans on your landing pages.',
    },
  },
  {
    id: 'social-posts',
    title: 'AI Social Post Writer',
    description: "Generate a week's worth of social content from a single link or topic.",
    icon: <Share2 />,
    color: 'from-rose-500/80 to-rose-600/80',
    synergies: {
      'ad-creation': 'Promote your ad campaigns across social media.',
      targeting: 'Write social posts that resonate with your target market.',
      rebranding: 'Generate a week of on-brand social content instantly.',
      'landing-pages': 'Drive social traffic to your beautiful new pages.',
      'social-posts': "The Megaphone: Amplify your message across every social channel.",
      'lead-gen': 'Use social media to drive traffic to your lead capture forms.',
      'competitor-analysis': 'See what kind of content is working for your competitors.',
      'market-analysis': 'Create posts about current market trends and news.',
      'auto-follow-up': 'Engage with social media commenters automatically.',
      'performance-dashboard': 'Track likes, shares, comments, and website clicks.',
      'email-campaigns': 'Promote your social media channels in your email newsletters.',
      'crm-integration': 'Capture leads from social media and add them to your CRM.',
      'brochure-rebrand': 'Post your newly rebranded brochures on social media.',
      'offer-management': 'Announce special offers and promotions on your social channels.',
      'calendar-sync': 'Share your availability for calls or meetings in your posts.',
      'bulk-actions': 'Schedule a whole month of social media posts in minutes.',
      'ai-chatbot': 'Use a chatbot to automatically respond to DMs.',
      'pdf-ads': 'Share your interactive PDF ads on platforms like LinkedIn.',
      'video-ads': 'Post your video ads on Instagram Reels, TikTok, and YouTube Shorts.',
      'content-syndication': 'Amplify your best social posts across multiple platforms.',
      'client-portal': 'Share social media performance updates with your clients.',
      'ai-negotiator': 'Use social media to gauge interest before starting negotiations.',
      'pms-integration': 'Announce new rental availabilities on social media.',
      'training-modules': 'Learn how to build a powerful real estate social media presence.',
      'virtual-tours': 'Post clips of your virtual tours to generate interest.',
      'roi-calculator': 'Create posts that show the potential ROI of an investment property.',
      'listing-management': 'Automatically create "Just Listed" posts for new properties.',
      'open-house-scheduler': 'Promote your open houses on Facebook and Instagram events.',
      'closing-assistance': 'Share "Just Sold" announcements and client testimonials.',
      'predictive-analytics': 'Predict which social media content will go viral.',
      'referral-program': 'Promote your referral program on your social channels.',
      'gamified-sales': 'Run social media contests for your followers.',
      'dynamic-pricing': 'Announce flash sales or limited-time offers on social media.',
      'a/b-testing': 'Test different post formats and captions to see what works best.',
      'local-seo': 'Use local hashtags and location tagging to boost visibility.',
      'community-engagement': 'Run polls, quizzes, and Q&A sessions to engage your audience.',
      'automated-reporting': 'Get weekly reports on your social media growth and engagement.',
      'script-generator': 'Generate ideas for social media video scripts.',
      'drip-campaigns': 'Move social media leads into your long-term nurture funnels.',
      'task-automation': 'Automatically create a task to respond to social media comments.',
      'feedback-surveys': 'Use social media polls to get quick feedback from your audience.',
      'real-time-alerts': 'Get an alert when your brand is mentioned on social media.',
      'compliance-checker': 'Ensure your social media posts meet advertising guidelines.',
      'document-generator': 'Share helpful checklists or guides as lead magnets.',
      'property-websites': 'Promote your beautiful property websites on social media.',
      'multi-language': 'Create social media content for different language demographics.',
      'voice-search': 'Create content that answers the questions people are asking.',
      'vr-staging': 'Share before-and-after virtual staging posts.',
      'market-reports': 'Share key insights from your market reports on social media.',
      'agent-collaboration': 'Amplify each other\'s posts by sharing and commenting.',
      'commission-tracking': 'Celebrate your team\'s successes on social media.',
      'social-listening': 'The core engine for finding new social post ideas.',
      'chat-integration': 'Drive social media traffic to a live chat on your website.',
      'contract-management': 'Share tips about navigating the contract process.',
      'showing-feedback': 'Post testimonials you receive from showing feedback.',
      'expense-tracking': 'Share how you invest in marketing to get the best results.',
      'brand-kit': 'Ensure all your social media posts are perfectly on-brand.',
      'interactive-maps': 'Share interesting location-based data and insights.',
      'event-promotion': 'Use social media to drive RSVPs to your events.',
      'content-calendar': 'The perfect companion to your AI social post writer.',
      '3d-floor-plans': 'Share walkthroughs of your 3D floor plans on social media.',
    },
  },
  {
    id: 'lead-gen',
    title: 'AI Lead Generation',
    description: 'Find and qualify high-intent buyers and sellers automatically.',
    icon: <Users />,
    color: 'from-teal-500/80 to-teal-600/80',
    synergies: {
      'ad-creation': 'Capture leads from every ad campaign.',
      targeting: 'Focus your efforts on the highest quality leads.',
      rebranding: 'A strong brand attracts better leads.',
      'landing-pages': 'The ultimate tool for converting traffic into leads.',
      'social-posts': 'Turn social engagement into tangible leads.',
      'lead-gen': 'The Magnet: Attract and qualify high-intent leads automatically.',
      'competitor-analysis': 'Find lead sources your competitors are ignoring.',
      'market-analysis': 'Generate leads by offering valuable market insights.',
      'auto-follow-up': 'The moment a lead comes in, the follow-up begins.',
      'performance-dashboard': 'Track your lead sources, cost per lead, and conversion rates.',
      'email-campaigns': 'Nurture your leads with targeted email campaigns.',
      'crm-integration': 'The heart of your lead management process.',
      'brochure-rebrand': 'Use rebranded brochures as powerful lead magnets.',
      'offer-management': 'Capture leads who are interested in making an offer.',
      'calendar-sync': 'Let qualified leads book meetings themselves.',
      'bulk-actions': 'Import and process lead lists in bulk.',
      'ai-chatbot': 'Your 24/7 lead qualifying and capturing machine.',
      'pdf-ads': 'Generate leads from professional documents.',
      'video-ads': 'Capture leads from your engaging video content.',
      'content-syndication': 'Generate leads from a network of content platforms.',
      'client-portal': 'Allow clients to see the leads being generated for their property.',
      'ai-negotiator': 'Qualify leads based on their negotiation behavior.',
      'pms-integration': 'Identify potential seller leads from your rental portfolio.',
      'training-modules': 'Become a lead generation expert.',
      'virtual-tours': 'Capture leads who are highly engaged with your virtual tours.',
      'roi-calculator': 'Offer a free ROI calculation in exchange for lead info.',
      'listing-management': 'Every listing is a potential lead magnet.',
      'open-house-scheduler': 'Capture leads from everyone who signs up for an open house.',
      'closing-assistance': 'Generate future leads from satisfied clients.',
      'predictive-analytics': 'The core of modern lead generation.',
      'referral-program': 'Turn your network into a lead generation engine.',
      'gamified-sales': 'Create competitions around lead generation goals.',
      'dynamic-pricing': 'Attract leads with flexible pricing options.',
      'a/b-testing': 'Optimize your lead capture forms for maximum conversion.',
      'local-seo': 'Generate a steady stream of local, organic leads.',
      'community-engagement': 'Build relationships that turn into leads.',
      'automated-reporting': 'Understand your lead flow like never before.',
      'script-generator': 'Equip your team with the best scripts for lead conversion.',
      'drip-campaigns': 'The perfect tool for long-term lead nurturing.',
      'task-automation': 'Automatically assign new leads to your agents.',
      'feedback-surveys': 'Get feedback from new leads to improve your process.',
      'real-time-alerts': 'The ultimate tool for speed-to-lead.',
      'compliance-checker': 'Ensure your lead generation methods are fully compliant.',
      'document-generator': 'Offer valuable documents to capture lead information.',
      'property-websites': 'Use property websites as your primary lead capture tool.',
      'multi-language': 'Generate leads from non-native speakers in your market.',
      'voice-search': 'Capture leads who are using voice to search for real estate.',
      'vr-staging': 'Offer exclusive access to virtually staged homes to capture leads.',
      'market-reports': 'The perfect lead magnet for buyers and sellers.',
      'agent-collaboration': 'Share leads and collaborate on follow-up with your team.',
      'commission-tracking': 'See exactly which lead sources generate the most revenue.',
      'social-listening': 'Find potential leads by listening to social conversations.',
      'chat-integration': 'Turn website chats into qualified leads in your CRM.',
      'contract-management': 'Identify potential leads from past contract interactions.',
      'showing-feedback': 'Identify highly interested buyers from showing feedback.',
      'expense-tracking': 'Analyze your cost-per-lead and optimize your spend.',
      'brand-kit': 'A consistent brand builds trust and improves lead quality.',
      'interactive-maps': 'Capture leads who are exploring specific neighborhoods.',
      'event-promotion': 'Generate leads from event attendees.',
      'content-calendar': 'Plan your lead generation campaigns visually.',
      '3d-floor-plans': 'Offer exclusive access to 3D floor plans to capture leads.',
    },
  },
  {
    id: 'competitor-analysis',
    title: 'Competitor Ad Analysis',
    description: 'See your competitors\' ads, targeting, and messaging.',
    icon: <Binoculars />,
    color: 'from-indigo-500/80 to-indigo-600/80',
    synergies: {
      'ad-creation': 'Create ads that are guaranteed to stand out.',
      targeting: 'Discover untapped audiences your competitors have missed.',
      rebranding: 'Position your brand to highlight your unique advantages.',
      'landing-pages': 'Build landing pages that convert better than your rivals\'.',
      'social-posts': 'Create social content that hijacks the conversation.',
      'lead-gen': 'Find lead sources that your competition doesn\'t know about.',
      'competitor-analysis': 'The Spyglass: See what\'s working for your competition.',
      'market-analysis': 'Combine competitor data with market trends for a complete picture.',
      'auto-follow-up': 'Craft follow-up messages that counter your competitors\' claims.',
      'performance-dashboard': 'Benchmark your performance against the competition.',
      'email-campaigns': 'Write email subject lines that win the inbox battle.',
      'crm-integration': 'Track which competitors your leads have also engaged with.',
      'brochure-rebrand': 'Design brochures that make your competitors look obsolete.',
      'offer-management': 'Make offers that your competitors can\'t match.',
      'calendar-sync': 'Offer more flexible showing times than your rivals.',
      'bulk-actions': 'Analyze dozens of competitors at once.',
      'ai-chatbot': 'Program your chatbot to handle competitor-related questions.',
      'pdf-ads': 'See what kind of professional content your competitors are sharing.',
      'video-ads': 'Analyze the production quality and messaging of competitor videos.',
      'content-syndication': 'See where your competitors are getting their content featured.',
      'client-portal': 'Show clients how your strategy is outperforming the competition.',
      'ai-negotiator': 'Know your competitors\' likely pricing to gain an edge.',
      'pms-integration': 'Analyze rental market competition.',
      'training-modules': 'Train your team on competitive analysis and positioning.',
      'virtual-tours': 'Offer a better virtual tour experience than your competitors.',
      'roi-calculator': 'Show clients why you provide better ROI than other agents.',
      'listing-management': 'Optimize your listings to rank higher than your competitors\'.',
      'open-house-scheduler': 'Schedule your open houses at times that don\'t conflict with rivals.',
      'closing-assistance': 'Offer a smoother closing process than your competitors.',
      'predictive-analytics': 'Predict your competitors\' next move.',
      'referral-program': 'Design a referral program that\'s more attractive than your rivals\'.',
      'gamified-sales': 'Create sales contests based on beating competitor benchmarks.',
      'dynamic-pricing': 'Stay one step ahead of your competitors\' pricing strategies.',
      'a/b-testing': 'Test your messaging against what your competitors are using.',
      'local-seo': 'Outrank your competitors for valuable local keywords.',
      'community-engagement': 'Be more active and visible in the community than your rivals.',
      'automated-reporting': 'Get weekly digests of your competitors\' marketing activities.',
      'script-generator': 'Prepare scripts that handle objections related to competitors.',
      'drip-campaigns': 'Create campaigns that highlight your advantages over the competition.',
      'task-automation': 'Get tasks to review top competitor activity weekly.',
      'feedback-surveys': 'Ask clients why they chose you over a competitor.',
      'real-time-alerts': 'Get alerted when a competitor launches a new campaign.',
      'compliance-checker': 'Check if your competitors are following advertising rules.',
      'document-generator': 'Create comparison sheets to show your value.',
      'property-websites': 'Build more engaging property websites than your rivals.',
      'multi-language': 'See if competitors are ignoring lucrative foreign-language markets.',
      'voice-search': 'Capture voice search traffic your competitors are missing.',
      'vr-staging': 'Offer better virtual staging than your competitors.',
      'market-reports': 'Provide more insightful market reports than your rivals.',
      'agent-collaboration': 'Team up to beat a dominant competitor in your market.',
      'commission-tracking': 'See how your commission rates compare to the market average.',
      'social-listening': 'The core of modern competitor analysis.',
      'chat-integration': 'Learn from the way your competitors handle live chat.',
      'contract-management': 'Offer more favorable contract terms than the competition.',
      'showing-feedback': 'See what buyers say about your competitors\' listings.',
      'expense-tracking': 'Analyze if your marketing spend is more efficient than your rivals\'.',
      'brand-kit': 'Develop a brand that stands in sharp contrast to your competitors.',
      'interactive-maps': 'Provide better local insights on your maps.',
      'event-promotion': 'Host more compelling events than your competitors.',
      'content-calendar': 'Anticipate and counter your competitors\' content schedule.',
      '3d-floor-plans': 'Provide more detailed and interactive floor plans.',
    },
  },
  {
    id: 'market-analysis',
    title: 'Real-Time Market Analysis',
    description: 'Access live data on pricing, trends, and inventory.',
    icon: <TrendingUp />,
    color: 'from-cyan-500/80 to-cyan-600/80',
    synergies: {
      'ad-creation': 'Create ads that reflect the current state of the market.',
      targeting: 'Target buyers who are looking in trending neighborhoods.',
      rebranding: 'Update your branding to match the latest market aesthetics.',
      'landing-pages': 'Incorporate live market stats on your landing pages.',
      'social-posts': 'Post daily or weekly market updates to engage your audience.',
      'lead-gen': 'Generate leads by offering exclusive market reports.',
      'competitor-analysis': 'See how your competitors are reacting to market changes.',
      'market-analysis': 'The Crystal Ball: See market trends before they happen.',
      'auto-follow-up': 'Send market update emails to your leads and clients.',
      'performance-dashboard': 'Correlate your performance with market movements.',
      'email-campaigns': 'Create data-driven email campaigns about market opportunities.',
      'crm-integration': 'Enrich your contacts with data about their local market.',
      'brochure-rebrand': 'Incorporate market data into your rebranded brochures.',
      'offer-management': 'Make competitive offers based on the latest comps.',
      'calendar-sync': 'Schedule meetings to discuss market trends with clients.',
      'bulk-actions': 'Apply market-based pricing adjustments to all your listings.',
      'ai-chatbot': 'Your chatbot can answer questions about market conditions.',
      'pdf-ads': 'Include market data charts in your PDF ads.',
      'video-ads': 'Create video content explaining complex market trends simply.',
      'content-syndication': 'Become a go-to source for market information.',
      'client-portal': 'Give clients a personalized view of their local market.',
      'ai-negotiator': 'Our AI uses real-time market data to negotiate effectively.',
      'pms-integration': 'Analyze rental market trends to advise your investor clients.',
      'training-modules': 'Learn how to interpret market data like a pro.',
      'virtual-tours': 'Highlight features that are currently trending in the market.',
      'roi-calculator': 'Use real-time data to create accurate ROI projections.',
      'listing-management': 'Price your listings perfectly based on live market data.',
      'open-house-scheduler': 'Schedule open houses when market data shows high buyer activity.',
      'closing-assistance': 'Advise clients on closing based on current market leverage.',
      'predictive-analytics': 'Forecast where the market is headed next.',
      'referral-program': 'Show referral partners how your market expertise benefits clients.',
      'gamified-sales': 'Create quizzes for your team based on market data.',
      'dynamic-pricing': 'The core engine for your dynamic pricing strategy.',
      'a/b-testing': 'Test how different market data points affect conversion rates.',
      'local-seo': 'Create content around local market trends to boost SEO.',
      'community-engagement': 'Host Q&A sessions about the local real estate market.',
      'automated-reporting': 'Send automated, personalized market reports to your clients.',
      'script-generator': 'Generate scripts that position you as the market expert.',
      'drip-campaigns': 'Nurture leads with long-term market trend updates.',
      'task-automation': 'Get reminders to review key market data weekly.',
      'feedback-surveys': 'Ask clients what market information they find most valuable.',
      'real-time-alerts': 'Get alerted to significant market shifts instantly.',
      'compliance-checker': 'Ensure your market data visualizations are clear and not misleading.',
      'document-generator': 'Generate CMAs and other reports with the latest data.',
      'property-websites': 'Include a "Market Trends" section on your property websites.',
      'multi-language': 'Provide market analysis in multiple languages.',
      'voice-search': 'Answer voice search questions about local market stats.',
      'vr-staging': 'Stage homes with furniture styles that are currently trending.',
      'market-reports': 'The ultimate tool for creating comprehensive market reports.',
      'agent-collaboration': 'Share market insights and strategies with your team.',
      'commission-tracking': 'See how market trends affect your earning potential.',
      'social-listening': 'Hear the real-time sentiment about the market from actual buyers.',
      'chat-integration': 'Answer user questions about market data in real-time.',
      'contract-management': 'Draft contracts that reflect current market conditions.',
      'showing-feedback': 'Correlate showing feedback with broader market trends.',
      'expense-tracking': 'Decide where to invest based on market opportunities.',
      'brand-kit': 'Develop a brand that communicates data-driven expertise.',
      'interactive-maps': 'Visualize market trends on an interactive map.',
      'event-promotion': 'Host "State of the Market" events for your clients.',
      'content-calendar': 'Plan your content around key market data releases.',
      '3d-floor-plans': 'Highlight floor plan features that are in high demand.',
    },
  },
  {
    id: 'auto-follow-up',
    title: 'Automated Follow-Up',
    description: 'Engage every lead instantly with personalized email and SMS sequences.',
    icon: <Repeat />,
    color: 'from-amber-500/80 to-amber-600/80',
    synergies: {
      'ad-creation': 'Instantly engage leads the moment they respond to an ad.',
      targeting: 'Customize follow-up sequences for different buyer personas.',
      rebranding: 'Ensure all your automated communications are perfectly on-brand.',
      'landing-pages': 'Trigger follow-up sequences as soon as a form is submitted.',
      'social-posts': 'Automatically respond to comments and direct messages.',
      'lead-gen': 'The key to converting new leads is speed-to-lead.',
      'competitor-analysis': 'Craft follow-up messages that counter competitor claims.',
      'market-analysis': 'Send automated market updates to your database.',
      'auto-follow-up': 'The Autopilot: Nurture leads and clients 24/7.',
      'performance-dashboard': 'Track open rates, click rates, and reply rates.',
      'email-campaigns': 'The engine for your automated email marketing.',
      'crm-integration': 'Trigger follow-up sequences based on lead status changes in your CRM.',
      'brochure-rebrand': 'Send your rebranded brochures as part of a follow-up sequence.',
      'offer-management': 'Automatically follow up on submitted or viewed offers.',
      'calendar-sync': 'Send automated reminders for scheduled appointments.',
      'bulk-actions': 'Enroll thousands of contacts into a follow-up sequence at once.',
      'ai-chatbot': 'Hand off conversations from your chatbot to an automated sequence.',
      'pdf-ads': 'Follow up with leads who have downloaded your PDF content.',
      'video-ads': 'Send follow-ups to people who have watched your video ads.',
      'content-syndication': 'Nurture leads from syndicated content with targeted follow-ups.',
      'client-portal': 'Send automated updates to your clients about their property.',
      'ai-negotiator': 'Automate the initial back-and-forth of a negotiation.',
      'pms-integration': 'Send automated rent reminders or maintenance updates.',
      'training-modules': 'Learn how to write effective follow-up copy.',
      'virtual-tours': 'Follow up with leads who have spent time on a virtual tour.',
      'roi-calculator': 'Send a detailed ROI report as part of a follow-up sequence.',
      'listing-management': 'Send automated "similar properties" emails to interested buyers.',
      'open-house-scheduler': 'Send reminders and thank you notes for open house attendees.',
      'closing-assistance': 'Automate the communication process during closing.',
      'predictive-analytics': 'Send follow-ups at the exact time a lead is most likely to engage.',
      'referral-program': 'Automatically ask for referrals after a successful closing.',
      'gamified-sales': 'Reward agents for having the best follow-up conversion rates.',
      'dynamic-pricing': 'Notify leads automatically when a price drops.',
      'a/b-testing': 'Test different follow-up cadences and messaging.',
      'local-seo': 'Follow up with leads who find you through local search.',
      'community-engagement': 'Automatically welcome new members to your community group.',
      'automated-reporting': 'See how your follow-up sequences are performing.',
      'script-generator': 'Generate scripts for your automated voicemails and video messages.',
      'drip-campaigns': 'The foundation of all your automated follow-up efforts.',
      'task-automation': 'Integrate automated communication with manual tasks.',
      'feedback-surveys': 'Automatically send feedback surveys after a showing or meeting.',
      'real-time-alerts': 'Trigger follow-up sequences based on real-time lead activity.',
      'compliance-checker': 'Ensure your automated messages are compliant with CAN-SPAM and TCPA.',
      'document-generator': 'Send relevant documents automatically based on lead behavior.',
      'property-websites': 'Follow up with users who save a property or create an account.',
      'multi-language': 'Send follow-up sequences in a lead\'s preferred language.',
      'voice-search': 'Provide automated answers to common voice search queries.',
      'vr-staging': 'Follow up with leads who have shown interest in a virtually staged property.',
      'market-reports': 'Send market reports as part of a long-term nurture sequence.',
      'agent-collaboration': 'Notify team members when a lead needs manual follow-up.',
      'commission-tracking': 'See which follow-up sequences lead to the most commissions.',
      'social-listening': 'Trigger automated responses based on social media keywords.',
      'chat-integration': 'Transition from a live chat to an automated follow-up sequence.',
      'contract-management': 'Send automated reminders for contract deadlines.',
      'showing-feedback': 'Automatically request feedback after a property showing.',
      'expense-tracking': 'Track the ROI of your automated follow-up systems.',
      'brand-kit': 'Ensure your automated messages always reflect your brand.',
      'interactive-maps': 'Send follow-ups based on the areas a lead is exploring.',
      'event-promotion': 'Send automated event reminders to registrants.',
      'content-calendar': 'Coordinate your follow-up campaigns with your content schedule.',
      '3d-floor-plans': 'Follow up with leads based on the floor plans they view.',
    },
  },
  {
    id: 'performance-dashboard',
    title: 'Performance Dashboard',
    description: 'Track every metric, from ad clicks to closed deals, in one place.',
    icon: <Gauge />,
    color: 'from-purple-500/80 to-purple-600/80',
    synergies: {
      'ad-creation': 'See which ads are performing best and double down.',
      targeting: 'Analyze the profitability of each target audience.',
      rebranding: 'Track how your rebrand is impacting engagement and conversions.',
      'landing-pages': 'Monitor conversion rates for all your landing pages.',
      'social-posts': 'Track likes, shares, comments, and click-through rates.',
      'lead-gen': 'Get a bird\'s-eye view of your entire lead funnel.',
      'competitor-analysis': 'Benchmark your key metrics against the competition.',
      'market-analysis': 'Correlate your performance with broader market trends.',
      'auto-follow-up': 'See which follow-up sequences are converting the best.',
      'performance-dashboard': 'The Command Center: Your entire business at a glance.',
      'email-campaigns': 'Track open rates, click rates, and unsubscribes.',
      'crm-integration': 'A single source of truth for all your sales and marketing data.',
      'brochure-rebrand': 'See if your new brochures are getting more engagement.',
      'offer-management': 'Track the number of offers received and their status.',
      'calendar-sync': 'See how many meetings are being booked and the show-up rate.',
      'bulk-actions': 'Analyze the collective impact of your bulk campaigns.',
      'ai-chatbot': 'Track how many conversations your chatbot is having and the leads generated.',
      'pdf-ads': 'Measure the engagement and lead gen from your PDF ads.',
      'video-ads': 'Track view-through rates, clicks, and conversions from your videos.',
      'content-syndication': 'See which syndication channels are driving the most traffic.',
      'client-portal': 'Provide your clients with a real-time performance dashboard.',
      'ai-negotiator': 'Track negotiation outcomes and identify patterns.',
      'pms-integration': 'Monitor occupancy rates, rent collection, and other KPIs.',
      'training-modules': 'Track your team\'s progress through training materials.',
      'virtual-tours': 'Analyze engagement data from your virtual tours.',
      'roi-calculator': 'Compare your projected ROI with your actual ROI.',
      'listing-management': 'See which listings are getting the most views and saves.',
      'open-house-scheduler': 'Track open house attendance and lead capture rates.',
      'closing-assistance': 'Monitor your time-to-close and other efficiency metrics.',
      'predictive-analytics': 'See how accurate your predictions are over time.',
      'referral-program': 'Track the number of referrals and the revenue they generate.',
      'gamified-sales': 'The dashboard is the scoreboard for your sales games.',
      'dynamic-pricing': 'See how pricing adjustments impact demand and revenue.',
      'a/b-testing': 'The place to see the results of all your A/B tests.',
      'local-seo': 'Track your search engine rankings and organic traffic.',
      'community-engagement': 'Measure the growth and engagement of your community.',
      'automated-reporting': 'The engine that powers your automated reports.',
      'script-generator': 'See which sales scripts are leading to the most conversions.',
      'drip-campaigns': 'Analyze the long-term performance of your nurture campaigns.',
      'task-automation': 'Track task completion rates and team productivity.',
      'feedback-surveys': 'Visualize feedback data to identify trends.',
      'real-time-alerts': 'See a live feed of all important activities.',
      'compliance-checker': 'Keep a dashboard of all your compliance-related activities.',
      'document-generator': 'Track how many documents are being generated and signed.',
      'property-websites': 'Monitor traffic, engagement, and lead capture on your sites.',
      'multi-language': 'See which languages are driving the most engagement.',
      'voice-search': 'Track the volume and type of voice queries you\'re answering.',
      'vr-staging': 'See if virtually staged homes get more views and sell faster.',
      'market-reports': 'Track how many people are downloading your market reports.',
      'agent-collaboration': 'A central dashboard for team performance.',
      'commission-tracking': 'The ultimate dashboard for tracking your earnings.',
      'social-listening': 'Get a dashboard of social sentiment and key trends.',
      'chat-integration': 'Analyze chat volume, response times, and conversion rates.',
      'contract-management': 'Keep track of all your contracts and their statuses.',
      'showing-feedback': 'Visualize showing feedback on a central dashboard.',
      'expense-tracking': 'A financial dashboard for your entire real estate business.',
      'brand-kit': 'Track the usage and consistency of your brand assets.',
      'interactive-maps': 'See which areas on the map get the most clicks.',
      'event-promotion': 'Track event registrations and attendance.',
      'content-calendar': 'Get a high-level view of all your scheduled marketing activities.',
      '3d-floor-plans': 'Track engagement with your 3D floor plans.',
    },
  },
  {
    id: 'email-campaigns',
    title: 'AI Email Campaigns',
    description: 'Create and automate beautiful, high-converting email blasts.',
    icon: <Mail />,
    color: 'from-lime-500/80 to-lime-600/80',
    synergies: {
      'ad-creation': 'Use ad visuals and copy in your email blasts.',
      targeting: 'Segment your email lists with incredible precision.',
      rebranding: 'Create beautiful, on-brand email templates in seconds.',
      'landing-pages': 'Drive email traffic to high-converting landing pages.',
      'social-posts': 'Promote your social channels and share posts in your newsletters.',
      'lead-gen': 'The cornerstone of nurturing leads into clients.',
      'competitor-analysis': 'Write subject lines that steal opens from competitors.',
      'market-analysis': 'Send data-driven market updates to your database.',
      'auto-follow-up': 'The engine for your automated email sequences.',
      'performance-dashboard': 'Track opens, clicks, and conversions for every campaign.',
      'email-campaigns': 'The Inbox Infiltrator: Create emails that get opened and clicked.',
      'crm-integration': 'Sync your email lists and campaign data with your CRM.',
      'brochure-rebrand': 'Send out your stunning rebranded brochures via email.',
      'offer-management': 'Email targeted offers to interested buyers.',
      'calendar-sync': 'Embed a link to your calendar in your email signature.',
      'bulk-actions': 'Send a campaign to thousands of contacts at once.',
      'ai-chatbot': 'Capture email subscribers through your chatbot.',
      'pdf-ads': 'Distribute your PDF ads to your email list.',
      'video-ads': 'Embed or link to your video ads in your emails.',
      'content-syndication': 'Promote your syndicated content in your newsletters.',
      'client-portal': 'Send email updates to clients about their property\'s performance.',
      'ai-negotiator': 'Conduct initial negotiations over email.',
      'pms-integration': 'Send newsletters or updates to your tenants.',
      'training-modules': 'Learn the art of writing compelling email copy.',
      'virtual-tours': 'Email exclusive virtual tours to your hottest leads.',
      'roi-calculator': 'Send personalized ROI calculations to investor leads.',
      'listing-management': 'Send "Just Listed" and "Open House" email announcements.',
      'open-house-scheduler': 'Email invitations and reminders for your open houses.',
      'closing-assistance': 'Keep clients informed during the closing process via email.',
      'predictive-analytics': 'Send emails at the optimal time for each recipient.',
      'referral-program': 'Email your past clients to ask for referrals.',
      'gamified-sales': 'Create sales contests based on email engagement metrics.',
      'dynamic-pricing': 'Email price drop alerts to interested buyers.',
      'a/b-testing': 'Test subject lines, content, and CTAs to optimize performance.',
      'local-seo': 'Build your email list through your locally optimized website.',
      'community-engagement': 'Send newsletters to your online community members.',
      'automated-reporting': 'Get reports on your email campaign performance.',
      'script-generator': 'Generate subject lines and email copy in seconds.',
      'drip-campaigns': 'The foundation of your automated email marketing.',
      'task-automation': 'Create tasks based on how leads interact with your emails.',
      'feedback-surveys': 'Email surveys to get feedback from your clients and leads.',
      'real-time-alerts': 'Get an alert when a hot lead opens your email.',
      'compliance-checker': 'Ensure your emails are CAN-SPAM compliant.',
      'document-generator': 'Email important documents for e-signature.',
      'property-websites': 'Drive email traffic to your property websites.',
      'multi-language': 'Send email campaigns in multiple languages.',
      'voice-search': 'Email content that answers common questions.',
      'vr-staging': 'Email virtually staged photos to potential buyers.',
      'market-reports': 'Use market reports as a lead magnet to build your email list.',
      'agent-collaboration': 'Share effective email templates with your team.',
      'commission-tracking': 'Track which email campaigns lead to the most revenue.',
      'social-listening': 'Get email content ideas from social conversations.',
      'chat-integration': 'Offer to continue a chat conversation via email.',
      'contract-management': 'Email contracts for review and signature.',
      'showing-feedback': 'Email feedback requests after a showing.',
      'expense-tracking': 'Track the ROI of your email marketing efforts.',
      'brand-kit': 'Ensure every email is perfectly on-brand.',
      'interactive-maps': 'Send emails with maps of available properties.',
      'event-promotion': 'The primary tool for promoting your events.',
      'content-calendar': 'Schedule your email campaigns alongside your other content.',
      '3d-floor-plans': 'Email interactive 3D floor plans to interested leads.',
    },
  },
  {
    id: 'crm-integration',
    title: 'Seamless CRM Integration',
    description: 'Sync all your data with the CRM you already use.',
    icon: <Network />,
    color: 'from-red-500/80 to-red-600/80',
    synergies: {
      'ad-creation': 'Pipe leads from ads directly into your CRM.',
      targeting: 'Enrich your CRM contacts with detailed targeting data.',
      rebranding: 'Brand consistency across all platforms.',
      'landing-pages': 'New leads from landing pages flow right into your CRM.',
      'social-posts': 'Capture leads from social media and add them to your CRM.',
      'lead-gen': 'The heart of your lead management process.',
      'competitor-analysis': 'Track which competitors your leads have also engaged with.',
      'market-analysis': 'Enrich contact profiles with market data.',
      'auto-follow-up': 'Trigger CRM workflows with our automation.',
      'performance-dashboard': 'Unify all your data for a 360-degree view.',
      'email-campaigns': 'Sync email lists and engagement data with your CRM.',
      'crm-integration': 'The Central Nervous System: Connect all your tools and data.',
      'brochure-rebrand': 'Log brochure sends and views on a contact\'s record.',
      'offer-management': 'Manage offers and negotiations within your CRM.',
      'calendar-sync': 'Sync meetings and appointments with your CRM contacts.',
      'bulk-actions': 'Update thousands of CRM records at once.',
      'ai-chatbot': 'Chat transcripts and new leads are saved to your CRM.',
      'pdf-ads': 'Log PDF views and downloads in your CRM.',
      'video-ads': 'Track video engagement on a contact\'s timeline.',
      'content-syndication': 'Attribute leads from syndicated content in your CRM.',
      'client-portal': 'Sync client activity with their CRM record.',
      'ai-negotiator': 'Log all negotiation activity in your CRM.',
      'pms-integration': 'Bi-directional sync between your PMS and CRM.',
      'training-modules': 'Track agent training progress in your CRM.',
      'virtual-tours': 'See which CRM contacts have viewed your tours.',
      'roi-calculator': 'Save ROI calculations to a contact or deal record.',
      'listing-management': 'Associate CRM contacts with listings they\'re interested in.',
      'open-house-scheduler': 'Open house attendees are automatically added to your CRM.',
      'closing-assistance': 'Manage your closing checklist within your CRM.',
      'predictive-analytics': 'Use CRM data to power your predictive models.',
      'referral-program': 'Track referral partners and their activity in your CRM.',
      'gamified-sales': 'Pull CRM data to power your sales leaderboards.',
      'dynamic-pricing': 'Log pricing adjustments on deal records.',
      'a/b-testing': 'Log test variants and results in your CRM.',
      'local-seo': 'Attribute website leads from SEO in your CRM.',
      'community-engagement': 'Add community members to your CRM for nurturing.',
      'automated-reporting': 'Generate reports using data from your CRM.',
      'script-generator': 'Save generated scripts to contact records.',
      'drip-campaigns': 'Trigger drip campaigns based on CRM contact status.',
      'task-automation': 'Create and manage tasks in your CRM.',
      'feedback-surveys': 'Save survey responses to contact records in your CRM.',
      'real-time-alerts': 'Trigger alerts based on CRM data changes.',
      'compliance-checker': 'Log consent and communication preferences in your CRM.',
      'document-generator': 'Generate documents using data from your CRM.',
      'property-websites': 'Website activity is logged on contact records in your CRM.',
      'multi-language': 'Store language preferences in your CRM.',
      'voice-search': 'Log voice queries and interactions in your CRM.',
      'vr-staging': 'Note which contacts have viewed staged properties.',
      'market-reports': 'Log market report downloads in your CRM.',
      'agent-collaboration': 'Collaborate on CRM records with your team.',
      'commission-tracking': 'Integrate with your CRM to automate commission calculations.',
      'social-listening': 'Create new CRM contacts from social media.',
      'chat-integration': 'Save chat transcripts to your CRM.',
      'contract-management': 'Manage your contracts as part of your CRM deals.',
      'showing-feedback': 'Log showing feedback on the relevant contact and deal records.',
      'expense-tracking': 'Associate expenses with specific CRM deals or contacts.',
      'brand-kit': 'Maintain data consistency between platforms.',
      'interactive-maps': 'Log which areas a contact is interested in within your CRM.',
      'event-promotion': 'Track event attendance in your CRM.',
      'content-calendar': 'Base your content on the data in your CRM.',
      '3d-floor-plans': 'See which floor plans your CRM contacts have viewed.',
    },
  },
  {
    id: 'brochure-rebrand',
    title: 'Brochure Rebranding',
    description: 'Upload any project brochure. Our AI instantly rebrands it.',
    icon: <FilePlus />,
    color: 'from-emerald-500/80 to-emerald-600/80',
    synergies: {
      'ad-creation': 'Use your rebranded brochures in your ad campaigns.',
      targeting: 'Create different brochure versions for different audiences.',
      rebranding: 'The core of your automated rebranding efforts.',
      'landing-pages': 'Offer your rebranded brochures as a download.',
      'social-posts': 'Share your beautifully rebranded brochures on social media.',
      'lead-gen': 'Use your rebranded brochures as powerful lead magnets.',
      'competitor-analysis': 'Create brochures that look better than your competitors\'.',
      'market-analysis': 'Incorporate market data into your rebranded brochures.',
      'auto-follow-up': 'Send your rebranded brochures in your follow-up sequences.',
      'performance-dashboard': 'Track downloads and views of your brochures.',
      'email-campaigns': 'Attach your rebranded brochures to your email campaigns.',
      'crm-integration': 'Log brochure sends and views in your CRM.',
      'brochure-rebrand': 'The Alchemist: Turn any brochure into branded gold.',
      'offer-management': 'Include a link to your rebranded brochure with every offer.',
      'calendar-sync': 'Send a brochure to leads before a scheduled meeting.',
      'bulk-actions': 'Rebrand and distribute brochures for all your listings at once.',
      'ai-chatbot': 'Your chatbot can offer to send a brochure to interested leads.',
      'pdf-ads': 'Your rebranded brochures can be used as PDF ads.',
      'video-ads': 'Create videos that walk through your rebranded brochure.',
      'content-syndication': 'Syndicate your rebranded brochures on other platforms.',
      'client-portal': 'Give clients access to their rebranded property brochures.',
      'ai-negotiator': 'Use the brochure as a reference point during negotiations.',
      'pms-integration': 'Create rebranded brochures for your rental listings.',
      'training-modules': 'Learn design principles to enhance your brochures.',
      'virtual-tours': 'Link to your virtual tour from your rebranded brochure.',
      'roi-calculator': 'Include an ROI calculation in your investor brochures.',
      'listing-management': 'A rebranded brochure for every single listing.',
      'open-house-scheduler': 'Have printed copies of your rebranded brochures at open houses.',
      'closing-assistance': 'Provide a beautifully branded closing package.',
      'predictive-analytics': 'Analyze which brochure designs get the most engagement.',
      'referral-program': 'Create a branded brochure explaining your referral program.',
      'gamified-sales': 'Challenge your team to create the best rebranded brochure.',
      'dynamic-pricing': 'Update pricing in your brochures automatically.',
      'a/b-testing': 'Test different versions of your brochures.',
      'local-seo': 'Make your brochures discoverable in local search.',
      'community-engagement': 'Create brochures for community events or sponsorships.',
      'automated-reporting': 'Track the performance of your rebranded brochures.',
      'script-generator': 'Generate compelling copy for your brochures.',
      'drip-campaigns': 'Use brochures as a key content piece in your drip campaigns.',
      'task-automation': 'Create a task to follow up with leads who download a brochure.',
      'feedback-surveys': 'Get feedback on your new brochure designs.',
      'real-time-alerts': 'Get an alert when someone downloads a brochure.',
      'compliance-checker': 'Ensure your brochures have all required legal text.',
      'document-generator': 'The foundation for generating other branded documents.',
      'property-websites': 'Offer brochure downloads on your property websites.',
      'multi-language': 'Rebrand brochures into multiple languages.',
      'voice-search': 'Make brochure content accessible to voice search.',
      'vr-staging': 'Include virtually staged photos in your brochures.',
      'market-reports': 'Create a branded brochure that summarizes a market report.',
      'agent-collaboration': 'Collaborate on brochure design with your team.',
      'commission-tracking': 'See which brochures lead to the most valuable clients.',
      'social-listening': 'Get ideas for your brochure content from social media.',
      'chat-integration': 'Offer to send a brochure during a live chat.',
      'contract-management': 'Keep your branding consistent from brochure to contract.',
      'showing-feedback': 'Send a thank-you note with a brochure after a showing.',
      'expense-tracking': 'Track the cost and ROI of your brochure marketing.',
      'brand-kit': 'The engine that powers your one-click brochure rebranding.',
      'interactive-maps': 'Embed QR codes to interactive maps in your brochures.',
      'event-promotion': 'Distribute branded brochures at your events.',
      'content-calendar': 'Schedule the release of your new brochures.',
      '3d-floor-plans': 'Include stunning 3D floor plans in your brochures.',
    },
  },
  {
    id: 'offer-management',
    title: 'Offer Management Portal',
    description: 'Receive, counter, and accept offers in one streamlined portal.',
    icon: <Handshake />,
    color: 'from-yellow-500/80 to-yellow-600/80',
    synergies: {
      'ad-creation': 'Send ad traffic to a dedicated offer portal.',
      'offer-management': 'The Deal Table: Manage offers and negotiations with ease.',
    },
  },
  {
    id: 'calendar-sync',
    title: 'Smart Calendar Sync',
    description: 'Sync your schedule and let qualified leads book meetings.',
    icon: <Calendar />,
    color: 'from-violet-500/80 to-violet-600/80',
    synergies: {
      'ad-creation': 'Let ad leads book meetings directly in your calendar.',
      'calendar-sync': 'The Time Saver: Automate your scheduling and never double-book.',
    },
  },
  {
    id: 'bulk-actions',
    title: 'Bulk Campaign Actions',
    description: 'Launch ads, emails, and updates across all listings at once.',
    icon: <ClipboardList />,
    color: 'from-stone-500/80 to-stone-600/80',
    synergies: {
      'ad-creation': 'Launch a dozen ad variations with a single click.',
      'bulk-actions': 'The Multiplier: Do in minutes what used to take days.',
    },
  },
  {
    id: 'ai-chatbot',
    title: '24/7 AI Chatbot',
    description: 'Engage and qualify website visitors, even when you\'re asleep.',
    icon: <Bot />,
    color: 'from-sky-500/80 to-sky-600/80',
    synergies: {
      'ad-creation': 'Qualify ad leads 24/7 with an AI assistant.',
      'ai-chatbot': 'The Night Owl: Your 24/7 sales assistant that never sleeps.',
    },
  },
  {
    id: 'pdf-ads',
    title: 'Interactive PDF Ads',
    description: 'Convert static PDFs into engaging, trackable lead magnets.',
    icon: <FileText />,
    color: 'from-fuchsia-500/80 to-fuchsia-600/80',
    synergies: {
      'ad-creation': 'Convert static PDFs into interactive, lead-generating ads.',
      'pdf-ads': 'The Document Dynamo: Turn any PDF into a lead machine.',
    },
  },
  {
    id: 'video-ads',
    title: 'AI Video Ad Generator',
    description: 'Create compelling short-form video ads from photos and text.',
    icon: <Video />,
    color: 'from-orange-400/80 to-orange-500/80',
    synergies: {
      'ad-creation': 'Generate compelling video ads that stop the scroll.',
      'video-ads': 'The Director: Create scroll-stopping video ads in seconds.',
    },
  },
  {
    id: 'content-syndication',
    title: 'Content Syndication',
    description: 'Automatically push your listings and content to partner sites.',
    icon: <Network />,
    color: 'from-green-400/80 to-green-500/80',
    synergies: {
      'ad-creation': 'Push your ad content across a network of platforms.',
      'content-syndication': 'The Amplifier: Get your content seen everywhere.',
    },
  },
  {
    id: 'client-portal',
    title: 'White-Label Client Portal',
    description: 'Give clients a branded, real-time view of their campaign performance.',
    icon: <Briefcase />,
    color: 'from-blue-400/80 to-blue-500/80',
    synergies: {
      'ad-creation': 'Give clients a real-time view of their ad campaigns.',
      'client-portal': 'The VIP Room: Give clients a branded, transparent experience.',
    },
  },
  {
    id: 'ai-negotiator',
    title: 'AI-Powered Negotiator',
    description: 'Let our AI handle initial offers and counter-offers for you.',
    icon: <BrainCircuit />,
    color: 'from-pink-400/80 to-pink-500/80',
    synergies: {
      'ad-creation': 'Let AI handle initial offers from ad leads.',
      'ai-negotiator': 'The Closer: Let AI handle the tough negotiations for you.',
    },
  },
  {
    id: 'pms-integration',
    title: 'PMS Integration',
    description: 'Sync with your property management software for seamless data flow.',
    icon: <Building />,
    color: 'from-teal-400/80 to-teal-500/80',
    synergies: {
      'ad-creation': 'Sync ad campaigns with your property management system.',
      'pms-integration': 'The Bridge: Connect your sales and property management data.',
    },
  },
  {
    id: 'training-modules',
    title: 'Agent Training Modules',
    description: 'Access a library of AI-powered training to sharpen your skills.',
    icon: <BookOpen />,
    color: 'from-indigo-400/80 to-indigo-500/80',
    synergies: {
      'ad-creation': 'Learn the secrets of high-converting ad copy.',
      'training-modules': 'The Dojo: Sharpen your skills and become a top producer.',
    },
  },
  {
    id: 'virtual-tours',
    title: 'Immersive Virtual Tours',
    description: 'Create and embed stunning 3D tours that captivate buyers.',
    icon: <Camera />,
    color: 'from-rose-400/80 to-rose-500/80',
    synergies: {
      'ad-creation': 'Embed immersive 3D tours directly into your ads.',
      'virtual-tours': 'The Holodeck: Let buyers walk through a home from anywhere.',
    },
  },
  {
    id: 'roi-calculator',
    title: 'ROI Calculator',
    description: 'Project and prove the value of an investment property.',
    icon: <DollarSign />,
    color: 'from-lime-400/80 to-lime-500/80',
    synergies: {
      'ad-creation': 'Project the potential return of your ad campaigns.',
      'roi-calculator': 'The Oracle: Prove the value of an investment with hard data.',
    },
  },
  {
    id: 'listing-management',
    title: 'Centralized Listing Management',
    description: 'Manage all your listings across all platforms from one place.',
    icon: <ClipboardCheck />,
    color: 'from-amber-400/80 to-amber-500/80',
    synergies: {
      'ad-creation': 'Create ads for all your listings automatically.',
      'listing-management': 'The Master Key: Manage all your listings in one place.',
    },
  },
  {
    id: 'open-house-scheduler',
    title: 'Open House Scheduler',
    description: 'Plan, promote, and manage open house attendance.',
    icon: <CalendarCheck />,
    color: 'from-purple-400/80 to-purple-500/80',
    synergies: {
      'ad-creation': 'Funnel ad traffic to open house sign-up forms.',
      'open-house-scheduler': 'The Host: Plan and promote flawless open houses.',
    },
  },
  {
    id: 'closing-assistance',
    title: 'AI Closing Assistant',
    description: 'Automate document collection and deadline reminders for smooth closings.',
    icon: <Key />,
    color: 'from-cyan-400/80 to-cyan-500/80',
    synergies: {
      'ad-creation': 'Generate all necessary closing docs from ad lead data.',
      'closing-assistance': 'The Concierge: Ensure every closing is smooth and stress-free.',
    },
  },
  {
    id: 'predictive-analytics',
    title: 'Predictive Analytics',
    description: 'Our AI predicts which leads will convert and which houses will sell.',
    icon: <Lightbulb />,
    color: 'from-red-400/80 to-red-500/80',
    synergies: {
      'ad-creation': 'Anticipate which ad creative will perform best.',
      'predictive-analytics': 'The Fortune Teller: Predict which leads will close.',
    },
  },
  {
    id: 'referral-program',
    title: 'Automated Referral Program',
    description: 'Turn your happy clients into a powerful referral engine.',
    icon: <Users />,
    color: 'from-emerald-400/80 to-emerald-500/80',
    synergies: {
      'ad-creation': 'Build referral campaigns to amplify your ads.',
      'referral-program': 'The Networker: Turn happy clients into your best sales force.',
    },
  },
  {
    id: 'gamified-sales',
    title: 'Gamified Sales Contests',
    description: 'Boost team motivation with leaderboards, badges, and rewards.',
    icon: <Award />,
    color: 'from-yellow-400/80 to-yellow-500/80',
    synergies: {
      'ad-creation': 'Create ad campaigns that drive friendly competition.',
      'gamified-sales': 'The Arena: Turn sales into a fun, competitive sport.',
    },
  },
  {
    id: 'dynamic-pricing',
    title: 'Dynamic Pricing Suggestions',
    description: 'Use AI to recommend the optimal price based on market data.',
    icon: <Sparkles />,
    color: 'from-violet-400/80 to-violet-500/80',
    synergies: {
      'ad-creation': 'Automatically adjust ad offers based on demand.',
      'dynamic-pricing': 'The Price is Right: Always know the perfect price.',
    },
  },
  {
    id: 'a/b-testing',
    title: 'A/B Testing Engine',
    description: 'Test everything from ad copy to email subject lines to find what works.',
    icon: <Filter />,
    color: 'from-stone-400/80 to-stone-500/80',
    synergies: {
      'ad-creation': 'Test multiple ad versions to find the winner.',
      'a/b-testing': 'The Scientist: Find out what really works with data.',
    },
  },
  {
    id: 'local-seo',
    title: 'Local SEO Booster',
    description: 'Dominate local search results and be the go-to agent in your area.',
    icon: <MapPin />,
    color: 'from-sky-400/80 to-sky-500/80',
    synergies: {
      'ad-creation': 'Boost your ad visibility in local search results.',
      'local-seo': 'The Mayor: Become the #1 agent in your local market.',
    },
  },
  {
    id: 'community-engagement',
    title: 'Community Engagement Tools',
    description: 'Build and manage your online community with AI-powered tools.',
    icon: <Headset />,
    color: 'from-fuchsia-400/80 to-fuchsia-500/80',
    synergies: {
      'ad-creation': 'Target community groups with tailored ads.',
      'community-engagement': 'The Town Square: Build a thriving online community.',
    },
  },
  {
    id: 'automated-reporting',
    title: 'Automated Client Reporting',
    description: 'Send beautiful, automated performance reports to your clients.',
    icon: <BarChart />,
    color: 'from-orange-300/80 to-orange-400/80',
    synergies: {
      'ad-creation': 'Send clients beautiful, automated ad performance reports.',
      'automated-reporting': 'The Analyst: Deliver stunning, automated reports.',
    },
  },
  {
    id: 'script-generator',
    title: 'AI Script Generator',
    description: 'Generate scripts for cold calls, video ads, and follow-up messages.',
    icon: <PenTool />,
    color: 'from-green-300/80 to-green-400/80',
    synergies: {
      'ad-creation': 'Generate scripts for video ads or sales calls.',
      'script-generator': 'The Playwright: Never be at a loss for words again.',
    },
  },
  {
    id: 'drip-campaigns',
    title: 'Long-Term Drip Campaigns',
    description: 'Nurture leads for months or even years with automated campaigns.',
    icon: <Mails />,
    color: 'from-blue-300/80 to-blue-400/80',
    synergies: {
      'ad-creation': 'Nurture ad leads with long-term, automated email drips.',
      'drip-campaigns': 'The Gardener: Nurture leads until they are ready to bloom.',
    },
  },
  {
    id: 'task-automation',
    title: 'Task Automation',
    description: 'Automate your to-do list and focus on what matters most.',
    icon: <ClipboardList />,
    color: 'from-pink-300/80 to-pink-400/80',
    synergies: {
      'ad-creation': 'Automatically create follow-up tasks for new ad leads.',
      'task-automation': 'The Butler: Let AI handle your busywork, so you can focus on clients.',
    },
  },
  {
    id: 'feedback-surveys',
    title: 'Automated Feedback Surveys',
    description: 'Collect valuable feedback from clients and leads automatically.',
    icon: <MessageCircle />,
    color: 'from-teal-300/80 to-teal-400/80',
    synergies: {
      'ad-creation': 'Survey ad respondents to refine your messaging.',
      'feedback-surveys': 'The Listener: Gather priceless feedback to constantly improve.',
    },
  },
  {
    id: 'real-time-alerts',
    title: 'Real-Time Activity Alerts',
    description: 'Get instant notifications for hot lead activity on your site.',
    icon: <Zap />,
    color: 'from-indigo-300/80 to-indigo-400/80',
    synergies: {
      'ad-creation': 'Get instant notifications for new ad leads.',
      'real-time-alerts': 'The Watchtower: Never miss an opportunity with instant alerts.',
    },
  },
  {
    id: 'compliance-checker',
    title: 'Compliance Checker',
    description: 'Ensure your marketing materials meet all regulatory standards.',
    icon: <ShieldCheck />,
    color: 'from-rose-300/80 to-rose-400/80',
    synergies: {
      'ad-creation': 'Ensure your ads meet all regulatory standards.',
      'compliance-checker': 'The Guardian: Stay safe and compliant with automated checks.',
    },
  },
  {
    id: 'document-generator',
    title: 'Document Generator',
    description: 'Automatically generate contracts, CMAs, and other documents.',
    icon: <FileUp />,
    color: 'from-lime-300/80 to-lime-400/80',
    synergies: {
      'ad-creation': 'Generate contracts from ad lead information.',
      'document-generator': 'The Scribe: Generate all your documents in a single click.',
    },
  },
  {
    id: 'property-websites',
    title: 'Single Property Websites',
    description: 'Create a stunning, dedicated website for each listing in minutes.',
    icon: <LayoutTemplate />,
    color: 'from-amber-300/80 to-amber-400/80',
    synergies: {
      'ad-creation': 'Create a unique website for each property you advertise.',
      'property-websites': 'The Architect: Build a stunning website for every listing.',
    },
  },
  {
    id: 'multi-language',
    title: 'Multi-Language Support',
    description: 'Translate your marketing materials into multiple languages.',
    icon: <MessageCircle />,
    color: 'from-purple-300/80 to-purple-400/80',
    synergies: {
      'ad-creation': 'Generate ads in multiple languages to reach a wider audience.',
      'multi-language': 'The Translator: Speak your clients\' language, literally.',
    },
  },
  {
    id: 'voice-search',
    title: 'Voice Search Optimization',
    description: 'Optimize your content to be found via voice assistants.',
    icon: <Headset />,
    color: 'from-cyan-300/80 to-cyan-400/80',
    synergies: {
      'ad-creation': 'Optimize your ad campaigns for voice search queries.',
      'voice-search': 'The Herald: Be the answer when clients ask Alexa or Siri.',
    },
  },
  {
    id: 'vr-staging',
    title: 'Virtual Reality Staging',
    description: 'Stage properties virtually to help buyers visualize their new home.',
    icon: <Gem />,
    color: 'from-red-300/80 to-red-400/80',
    synergies: {
      'ad-creation': 'Use virtually staged photos in your property ads.',
      'vr-staging': 'The Dream Weaver: Stage any home virtually to inspire buyers.',
    },
  },
  {
    id: 'market-reports',
    title: 'Hyper-Local Market Reports',
    description: 'Generate beautiful, data-rich reports for any neighborhood.',
    icon: <FileSearch />,
    color: 'from-emerald-300/80 to-emerald-400/80',
    synergies: {
      'ad-creation': 'Incorporate hyper-local market data into your ads.',
      'market-reports': 'The Town Crier: Generate hyper-local reports that build trust.',
    },
  },
  {
    id: 'agent-collaboration',
    title: 'Team Collaboration Tools',
    description: 'Collaborate with your team on listings, leads, and campaigns.',
    icon: <Users />,
    color: 'from-yellow-300/80 to-yellow-400/80',
    synergies: {
      'ad-creation': 'Collaborate with your team on ad campaigns.',
      'agent-collaboration': 'The Round Table: Achieve more by working together seamlessly.',
    },
  },
  {
    id: 'commission-tracking',
    title: 'Commission Tracking',
    description: 'Track your commissions and get projections for future earnings.',
    icon: <LineChart />,
    color: 'from-violet-300/80 to-violet-400/80',
    synergies: {
      'ad-creation': 'Track commissions earned from ad-generated leads.',
      'commission-tracking': 'The Treasurer: Watch your earnings grow in real-time.',
    },
  },
  {
    id: 'social-listening',
    title: 'Social Media Listening',
    description: 'Track mentions of your brand and identify potential leads.',
    icon: <Binoculars />,
    color: 'from-stone-300/80 to-stone-400/80',
    synergies: {
      'ad-creation': 'Discover new ad angles by listening to social conversations.',
      'social-listening': 'The Ear: Hear what people are saying and find hidden opportunities.',
    },
  },
  {
    id: 'chat-integration',
    title: 'Live Chat Integration',
    description: 'Add live chat to your website and talk to visitors in real-time.',
    icon: <MessageCircle />,
    color: 'from-sky-300/80 to-sky-400/80',
    synergies: {
      'ad-creation': 'Engage with ad leads instantly via live chat.',
      'chat-integration': 'The Concierge Desk: Be there for your clients, instantly.',
    },
  },
  {
    id: 'contract-management',
    title: 'Contract Management',
    description: 'Manage the entire lifecycle of your contracts, from draft to signature.',
    icon: <FileText />,
    color: 'from-fuchsia-300/80 to-fuchsia-400/80',
    synergies: {
      'ad-creation': 'Manage the entire contract lifecycle from an ad lead.',
      'contract-management': 'The Dealmaker: Streamline your contracts from draft to signature.',
    },
  },
  {
    id: 'showing-feedback',
    title: 'Automated Showing Feedback',
    description: 'Automatically request and collect feedback after every showing.',
    icon: <ClipboardCheck />,
    color: 'from-orange-200/80 to-orange-300/80',
    synergies: {
      'ad-creation': 'Collect feedback from showings generated by your ads.',
      'showing-feedback': 'The Critic: Get honest feedback to sell homes faster.',
    },
  },
  {
    id: 'expense-tracking',
    title: 'Expense Tracking',
    description: 'Track all your business expenses and see where your money is going.',
    icon: <DollarSign />,
    color: 'from-green-200/80 to-green-300/80',
    synergies: {
      'ad-creation': 'Track every dollar spent on your ad campaigns.',
      'expense-tracking': 'The Accountant: Keep your finances in perfect order, effortlessly.',
    },
  },
  {
    id: 'brand-kit',
    title: 'Centralized Brand Kit',
    description: 'Store your logos, colors, and fonts for easy access.',
    icon: <Briefcase />,
    color: 'from-blue-200/80 to-blue-300/80',
    synergies: {
      'ad-creation': 'Ensure all your ads are perfectly on-brand.',
      'brand-kit': 'The Style Guide: Ensure perfect brand consistency, every time.',
    },
  },
  {
    id: 'interactive-maps',
    title: 'Interactive Property Maps',
    description: 'Create beautiful, interactive maps of your listings.',
    icon: <MapPin />,
    color: 'from-pink-200/80 to-pink-300/80',
    synergies: {
      'ad-creation': 'Include interactive maps in your ad landing pages.',
      'interactive-maps': 'The Cartographer: Bring your listings and neighborhoods to life.',
    },
  },
  {
    id: 'event-promotion',
    title: 'Event Promotion Tools',
    description: 'Promote your open houses, webinars, and other events.',
    icon: <Megaphone />,
    color: 'from-teal-200/80 to-teal-300/80',
    synergies: {
      'ad-creation': 'Promote open houses and other events with targeted ads.',
      'event-promotion': 'The Party Planner: Pack your events with the right people.',
    },
  },
  {
    id: 'content-calendar',
    title: 'Content Calendar',
    description: 'Plan and schedule all your content in one visual calendar.',
    icon: <Calendar />,
    color: 'from-indigo-200/80 to-indigo-300/80',
    synergies: {
      'ad-creation': 'Schedule your ad campaigns in a visual calendar.',
      'content-calendar': 'The Strategist: Plan your marketing for months in advance.',
    },
  },
  {
    id: '3d-floor-plans',
    title: '3D Floor Plan Generator',
    description: 'Turn standard floor plans into immersive 3D models.',
    icon: <Gem />,
    color: 'from-rose-200/80 to-rose-300/80',
    synergies: {
      'ad-creation': 'Showcase properties with immersive 3D floor plans in your ads.',
      '3d-floor-plans': 'The Dollhouse: Let buyers explore a home in stunning 3D.',
    },
  },
];


const FeatureCard = ({
  feature,
  index,
  hoveredId,
  setHoveredId,
  onClick,
}: {
  feature: (typeof features)[0];
  index: number;
  hoveredId: string | null;
  setHoveredId: (id: string | null) => void;
  onClick: (id: string) => void;
}) => {
  const isHovered = hoveredId === feature.id;
  const isSomeoneElseHovered = hoveredId !== null && !isHovered;

  const getCardState = () => {
    if (isHovered) return 'active';
    if (isSomeoneElseHovered) return 'synergy';
    return 'default';
  };
  
  const cardState = getCardState();
  const synergyText = hoveredId ? (features.find(f => f.id === hoveredId)?.synergies as any)?.[feature.id] : null;

  return (
    <div
      className="group flex flex-col [perspective:1000px] animate-fade-in-up"
      style={{ animationDelay: `${index * 20}ms` }}
      onMouseEnter={() => setHoveredId(feature.id)}
    >
      <div
        className={cn(
          'relative w-full h-[420px] text-white transition-transform duration-700 ease-in-out rounded-3xl',
          '[transform-style:preserve-3d]',
          cardState === 'active' && '[transform:rotateY(180deg)]',
          cardState === 'synergy' && 'group-hover/main:animate-float'
        )}
      >
        {/* Front of the card */}
        <div
          className={cn(
            'absolute inset-0 flex flex-col justify-between p-8 bg-gradient-to-br rounded-3xl',
            'transition-opacity duration-500',
            feature.color,
            '[backface-visibility:hidden]',
            cardState === 'synergy' && 'opacity-0' 
          )}
        >
            <div className="z-10 flex flex-col h-full">
              <div className="mb-4 p-3 bg-white/20 rounded-full w-fit">
                {React.cloneElement(feature.icon, { className: 'h-8 w-8' })}
              </div>
              <h2 className="text-3xl font-bold mb-3">{feature.title}</h2>
              <p className="text-lg opacity-90 flex-grow">{feature.description}</p>
              <Button
                size="lg"
                variant="ghost"
                className={cn(
                    'bg-white/10 hover:bg-white/20 text-white w-full backdrop-blur-sm border border-white/20 mt-auto',
                    cardState === 'synergy' && 'hidden'
                )}
                onClick={() => onClick(feature.id)}
              >
                {isHovered ? (
                  <>
                    Explore Synergy
                    <Zap className="ml-2 transition-transform duration-300 group-hover:translate-x-1" />
                  </>
                ) : (
                  <>
                    Learn more
                    <ArrowRight className="ml-2 transition-transform duration-300 group-hover:translate-x-1" />
                  </>
                )}
              </Button>
            </div>
        </div>

        {/* Back of the card - Active State */}
        <div
          className={cn(
            'absolute inset-0 flex flex-col items-center justify-center p-8 bg-gradient-to-br rounded-3xl',
            feature.color,
            '[backface-visibility:hidden] [transform:rotateY(180deg)]'
          )}
        >
            <h3 className="text-4xl font-bold text-center drop-shadow-lg">
              { (feature.synergies as any)[feature.id] || "Unlock Potential"}
            </h3>
        </div>
        
        {/* Third Face - Synergy State */}
        {synergyText && (
          <div
            className={cn(
              'absolute inset-0 flex flex-col items-center justify-center p-8 bg-gradient-to-br rounded-3xl',
              features.find(f => f.id === hoveredId)?.color,
              'transition-opacity duration-500 ease-in-out',
               cardState === 'synergy' ? 'opacity-100' : 'opacity-0',
              '[backface-visibility:hidden] '
            )}
          >
            <div className="text-center">
              <Zap className="h-12 w-12 text-white/80 mx-auto mb-4" />
              <h3 className="text-2xl font-bold text-center text-white">
                {synergyText}
              </h3>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};


export default function Home() {
  const { toast } = useToast();
  const [hoveredId, setHoveredId] = React.useState<string | null>(null);
  const [clickedCards, setClickedCards] = React.useState<Set<string>>(new Set());
  const [showConfetti, setShowConfetti] = React.useState(false);

  const handleCardClick = (id: string) => {
    const newClicked = new Set(clickedCards);
    newClicked.add(id);
    setClickedCards(newClicked);

    if (newClicked.size === 1) {
      toast({
        title: "Great start! ✨",
        description: "Click two more cards to see the magic.",
      });
    } else if (newClicked.size === 3) {
      toast({
        title: "Awesome! You're getting it. 🚀",
        description: "The possibilities are endless.",
      });
      setShowConfetti(true);
    }
  };

  return (
    <div className="flex min-h-screen flex-col bg-background">
      {showConfetti && <Confetti />}
      <LandingHeader />
      <main className="flex-1 w-full max-w-full px-4 md:px-6 lg:px-8 py-12 md:py-20">
        <div className="text-center mb-16 max-w-5xl mx-auto">
          <h1 className="text-4xl md:text-7xl font-bold tracking-tighter mb-4 bg-clip-text text-transparent bg-gradient-to-b from-foreground/90 to-foreground/60">
            Your Real Estate Sales, Amplified.
          </h1>
          <p className="text-lg md:text-xl text-foreground/60">
            Unlock AI-powered tools to create stunning marketing, find
            high-intent buyers, and close deals faster. Level up your sales
            game.
          </p>
          <div className="mt-8 flex gap-4 justify-center">
            <Button size="lg" className="text-lg py-7 px-8">Start Your Free Trial</Button>
            <Button size="lg" variant="outline" className="text-lg py-7 px-8">
              See it in Action
            </Button>
          </div>
        </div>

        <div 
            className="group/main grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5 gap-8 lg:gap-12 max-w-[120rem] mx-auto"
            onMouseLeave={() => setHoveredId(null)}
        >
          {features.map((feature, index) => (
            <FeatureCard 
                key={feature.id} 
                feature={feature} 
                index={index} 
                hoveredId={hoveredId}
                setHoveredId={setHoveredId}
                onClick={handleCardClick}
            />
          ))}
        </div>
      </main>
      <LandingFooter />
    </div>
  );
}
