
'use client';

import React from 'react';
import {
  ArrowRight,
  Bot,
  FileUp,
  LayoutTemplate,
  Palette,
  Target,
  Share2,
  Gem,
  Sparkles,
  Gauge,
  Mails,
  Binoculars,
  Video,
  BarChart,
  Repeat,
  CalendarCheck,
  Award,
  Megaphone,
  Zap,
  Users,
  TrendingUp,
  Filter,
  Lightbulb,
  ShieldCheck,
  BrainCircuit,
  ClipboardCheck,
  FileText,
  Clock,
  Briefcase,
  PenTool,
  MessageCircle,
  Mail,
  Calendar,
  DollarSign,
  MapPin,
  ClipboardList,
  FilePlus,
  Network,
  Handshake,
  Headset,
  BookOpen,
  Camera,
  LineChart,
  FileSearch,
  Building,
  Key,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import { LandingHeader } from '@/components/landing-header';
import { LandingFooter } from '@/components/landing-footer';
import { Confetti } from '@/components/confetti';
import { useToast } from '@/hooks/use-toast';

const features = [
  {
    id: 'ad-creation',
    title: 'Instant Ad Creation',
    description: 'Generate high-performance ad copy and visuals from any brochure in seconds.',
    icon: <Megaphone />,
    color: 'from-pink-500/80 to-pink-600/80',
    isIntro: true,
    synergies: {
      'ad-creation': "Genesis: Spark brilliant campaigns.",
      targeting: 'Fine-tune with buyer personas.',
      rebranding: 'Match your new brand.',
      'landing-pages': 'Drive traffic to pages.',
      'social-posts': 'Turn concepts into blitz.',
      'lead-gen': 'Capture every lead.',
      'competitor-analysis': 'Outperform your biggest rivals.',
      'market-analysis': 'Base ads on trends.',
      'auto-follow-up': 'Instantly engage ad respondents.',
      'performance-dashboard': 'Track ad spend, ROI.',
      'email-campaigns': 'Use visuals in emails.',
      'crm-integration': 'Pipe leads to CRM.',
      'brochure-rebrand': 'Branded masterpiece from brochure.',
      'offer-management': 'Drive traffic to portal.',
      'calendar-sync': 'Leads book meetings directly.',
      'bulk-actions': 'Launch a dozen variations.',
      'ai-chatbot': 'Qualify leads 24/7.',
      'pdf-ads': 'Convert PDFs to ads.',
      'video-ads': 'Generate compelling video ads.',
      'content-syndication': 'Push content across platforms.',
      'client-portal': 'Give clients real-time view.',
      'ai-negotiator': 'AI handles initial offers.',
      'pms-integration': 'Sync with your PMS.',
      'training-modules': 'Learn high-converting copy.',
      'virtual-tours': 'Embed 3D tours.',
      'roi-calculator': 'Project ad campaign return.',
      'listing-management': 'Create ads automatically.',
      'open-house-scheduler': 'Funnel traffic to sign-ups.',
      'closing-assistance': 'Generate docs from leads.',
      'predictive-analytics': 'Anticipate best creative.',
      'referral-program': 'Amplify ads with referrals.',
      'gamified-sales': 'Drive friendly competition.',
      'dynamic-pricing': 'Adjust offers based on demand.',
      'a/b-testing': 'Test versions, find winner.',
      'local-seo': 'Boost visibility locally.',
      'community-engagement': 'Target groups with ads.',
      'automated-reporting': 'Send automated performance reports.',
      'script-generator': 'Generate video ad scripts.',
      'drip-campaigns': 'Nurture leads long-term.',
      'task-automation': 'Create new lead tasks.',
      'feedback-surveys': 'Refine messaging with surveys.',
      'real-time-alerts': 'Instant new lead notifications.',
      'compliance-checker': 'Ensure ads meet standards.',
      'document-generator': 'Generate contracts from leads.',
      'property-websites': 'Create unique property websites.',
      'multi-language': 'Generate ads in many languages.',
      'voice-search': 'Optimize for voice queries.',
      'vr-staging': 'Use virtually staged photos.',
      'market-reports': 'Incorporate hyper-local data.',
      'agent-collaboration': 'Collaborate on ad campaigns.',
      'commission-tracking': 'Track ad-generated commissions.',
      'social-listening': 'Discover new ad angles.',
      'chat-integration': 'Engage leads via chat.',
      'contract-management': 'Manage contracts from leads.',
      'showing-feedback': 'Collect feedback from showings.',
      'expense-tracking': 'Track all ad spend.',
      'brand-kit': 'Ensure ads are on-brand.',
      'interactive-maps': 'Include maps in pages.',
      'event-promotion': 'Promote events with ads.',
      'content-calendar': 'Schedule ad campaigns visually.',
      '3d-floor-plans': 'Showcase with 3D plans.',
    },
  },
  {
    id: 'targeting',
    title: 'Precision Targeting',
    description: 'Our AI analyzes your project and identifies high-intent buyers.',
    icon: <Target />,
    color: 'from-blue-500/80 to-blue-600/80',
    isIntro: true,
    synergies: {
      'ad-creation': 'Power ads with audience.',
      'targeting': "Bullseye: Zero in on profits.",
      rebranding: 'Rebrand for niche markets.',
      'landing-pages': 'Drive high-intent buyers.',
      'social-posts': 'Tailor content to demos.',
      'lead-gen': 'Focus efforts on people.',
      'competitor-analysis': 'Find competitor\'s missed audiences.',
      'market-analysis': 'Target based on shifts.',
      'auto-follow-up': 'Customize buyer segment sequences.',
      'performance-dashboard': 'See profitable audience segments.',
      'email-campaigns': 'Segment lists with precision.',
      'crm-integration': 'Enrich CRM with data.',
      'brochure-rebrand': 'Adapt brochures to personas.',
      'offer-management': 'Send targeted offers.',
      'calendar-sync': 'Allow pre-qualified bookings.',
      'bulk-actions': 'Apply profiles across campaigns.',
      'ai-chatbot': 'Different personalities for audiences.',
      'pdf-ads': 'Target specific professional groups.',
      'video-ads': 'Create videos for personas.',
      'content-syndication': 'Syndicate where audience lives.',
      'client-portal': 'Show clients marketing reach.',
      'ai-negotiator': 'Adjust tactics by profile.',
      'pms-integration': 'Identify buyers from tenants.',
      'training-modules': 'Master psychographic behavioral targeting.',
      'virtual-tours': 'See demographic 3D engagement.',
      'roi-calculator': 'Calculate ROI for campaigns.',
      'listing-management': 'Match listings to profile.',
      'open-house-scheduler': 'Target invites to buyers.',
      'closing-assistance': 'Anticipate different buyer needs.',
      'predictive-analytics': 'Predict valuable buyer segments.',
      'referral-program': 'Target requests to clients.',
      'gamified-sales': 'Create team targeting challenges.',
      'dynamic-pricing': 'Offer prices to segments.',
      'a/b-testing': 'Test audience messaging response.',
      'local-seo': 'Dominate local search.',
      'community-engagement': 'Engage with niche communities.',
      'automated-reporting': 'Generate valuable targeting reports.',
      'script-generator': 'Create tailored sales scripts.',
      'drip-campaigns': 'Develop unique buyer campaigns.',
      'task-automation': 'Assign leads to agents.',
      'feedback-surveys': 'Get feedback, refine strategy.',
      'real-time-alerts': 'Alert on prospect activity.',
      'compliance-checker': 'Ensure fair, compliant targeting.',
      'document-generator': 'Pre-populate docs with data.',
      'property-websites': 'Create sites for audiences.',
      'multi-language': 'Target audiences in native language.',
      'voice-search': 'Optimize for audience questions.',
      'vr-staging': 'See appealing virtual styles.',
      'market-reports': 'Provide targeted market reports.',
      'agent-collaboration': 'Assign agents to leads.',
      'commission-tracking': 'Analyze commission by source.',
      'social-listening': 'Find audience by listening.',
      'chat-integration': 'Route chats to agents.',
      'contract-management': 'Use different contract templates.',
      'showing-feedback': 'Analyze feedback by demos.',
      'expense-tracking': 'Allocate budget to segments.',
      'brand-kit': 'Adapt brand for audiences.',
      'interactive-maps': 'Highlight features for buyers.',
      'event-promotion': 'Promote to likely attendees.',
      'content-calendar': 'Plan around audience interests.',
      '3d-floor-plans': 'Customize for family lifestyles.',
    },
  },
  {
    id: 'rebranding',
    title: 'Automated Rebranding',
    description: 'Instantly rebrand any brochure with your logo, colors, and voice.',
    icon: <Palette />,
    color: 'from-orange-500/80 to-orange-600/80',
    isIntro: true,
    synergies: {
      'ad-creation': 'Generate on-brand ads.',
      targeting: 'Adapt voice for segments.',
      'rebranding': "Makeover: Instantly apply brand.",
      'landing-pages': 'Brand landing pages instantly.',
      'social-posts': 'Maintain consistent brand voice.',
      'lead-gen': 'Match forms to brand.',
      'competitor-analysis': 'Differentiate your brand.',
      'market-analysis': 'Match current design trends.',
      'auto-follow-up': 'On-brand automated emails.',
      'performance-dashboard': 'Customize with your branding.',
      'email-campaigns': 'Create on-brand email templates.',
      'crm-integration': 'Consistent identity across platforms.',
      'brochure-rebrand': 'Effortless, core rebranding.',
      'offer-management': 'Brand portal, build trust.',
      'calendar-sync': 'Booking page reflects brand.',
      'bulk-actions': 'Apply branding to listings.',
      'ai-chatbot': 'Chatbot speaks brand\'s voice.',
      'pdf-ads': 'Brand stands out in PDFs.',
      'video-ads': 'Apply brand to videos.',
      'content-syndication': 'Syndicate branded content.',
      'client-portal': 'Offer white-labeled portal.',
      'ai-negotiator': 'Reflect brand professionalism.',
      'pms-integration': 'Consistent property management comms.',
      'training-modules': 'Train team on brand.',
      'virtual-tours': 'Add logo to tours.',
      'roi-calculator': 'Branded ROI calculation reports.',
      'listing-management': 'On-brand listing detail pages.',
      'open-house-scheduler': 'Brand open house sign-ups.',
      'closing-assistance': 'Branded closing documents.',
      'predictive-analytics': 'Analyze brand consistency impact.',
      'referral-program': 'Create branded referral portal.',
      'gamified-sales': 'Use brand in leaderboards.',
      'dynamic-pricing': 'Branded pricing and offers.',
      'a/b-testing': 'Test different brand messages.',
      'local-seo': 'Build local search authority.',
      'community-engagement': 'Engage with brand persona.',
      'automated-reporting': 'Perfectly branded client reports.',
      'script-generator': 'Generate on-brand scripts.',
      'drip-campaigns': 'Consistently branded nurture campaigns.',
      'task-automation': 'Branded templates for comms.',
      'feedback-surveys': 'Surveys match brand identity.',
      'real-time-alerts': 'Customize alert notifications.',
      'compliance-checker': 'Record branded communications.',
      'document-generator': 'Generate branded documents.',
      'property-websites': 'Spin up branded websites.',
      'multi-language': 'Ensure brand voice translation.',
      'voice-search': 'Brand name in voice strategy.',
      'vr-staging': 'Apply branded virtual furniture.',
      'market-reports': 'Reports reflect brand expertise.',
      'agent-collaboration': 'Ensure team uses branding.',
      'commission-tracking': 'Branded earnings dashboard.',
      'social-listening': 'Track online brand perception.',
      'chat-integration': 'Chat widget matches website.',
      'contract-management': 'Brand the contract experience.',
      'showing-feedback': 'Branded feedback survey forms.',
      'expense-tracking': 'Branded expense organization.',
      'brand-kit': 'Central hub for rebranding.',
      'interactive-maps': 'Customize map styles.',
      'event-promotion': 'Consistently branded event materials.',
      'content-calendar': 'Visualize on-brand content.',
      '3d-floor-plans': 'Add brand watermark.',
    },
  },
  {
    id: 'landing-pages',
    title: 'Landing Page Generator',
    description: 'Generate persuasive landing pages that captivate buyers.',
    icon: <LayoutTemplate />,
    color: 'from-green-500/80 to-green-600/80',
    isIntro: true,
    synergies: {
      'ad-creation': 'Perfect destination for clicks.',
      targeting: 'Build pages for audiences.',
      rebranding: 'Generate branded pages.',
      'landing-pages': "Engine: Turn clicks to clients.",
      'social-posts': 'Link posts to pages.',
      'lead-gen': 'Pages are lead machines.',
      'competitor-analysis': 'Build better pages.',
      'market-analysis': 'Update content with data.',
      'auto-follow-up': 'Trigger sequences from leads.',
      'performance-dashboard': 'Track views, bounces, conversions.',
      'email-campaigns': 'Destination for email CTAs.',
      'crm-integration': 'Leads flow to CRM.',
      'brochure-rebrand': 'Use assets on pages.',
      'offer-management': 'Embed portal into page.',
      'calendar-sync': 'Allow booking from page.',
      'bulk-actions': 'Create pages for listings.',
      'ai-chatbot': 'Add chatbot to pages.',
      'pdf-ads': 'Create pages for campaigns.',
      'video-ads': 'Embed videos on pages.',
      'content-syndication': 'Drive traffic to pages.',
      'client-portal': 'Create pages for clients.',
      'ai-negotiator': 'Start negotiation from page.',
      'pms-integration': 'Create pages for rentals.',
      'training-modules': 'Learn high-converting design.',
      'virtual-tours': 'Centerpiece of your pages.',
      'roi-calculator': 'Add calculator to pages.',
      'listing-management': 'Generate page per listing.',
      'open-house-scheduler': 'Sign-up for open houses.',
      'closing-assistance': 'Create secure document portal.',
      'predictive-analytics': 'Predict best page designs.',
      'referral-program': 'Create referral sign-up page.',
      'gamified-sales': 'Contests on conversion rates.',
      'dynamic-pricing': 'Show personalized pricing.',
      'a/b-testing': 'Test headlines, images, CTAs.',
      'local-seo': 'Optimize for local terms.',
      'community-engagement': 'Create pages for events.',
      'automated-reporting': 'See lead-generating pages.',
      'script-generator': 'Generate compelling copy.',
      'drip-campaigns': 'Enroll leads in campaigns.',
      'task-automation': 'Create tasks from forms.',
      'feedback-surveys': 'Add survey to page.',
      'real-time-alerts': 'Alert on lead capture.',
      'compliance-checker': 'Ensure pages have disclaimers.',
      'document-generator': 'Allow sample doc generation.',
      'property-websites': 'Page can be micro-site.',
      'multi-language': 'Create page language variations.',
      'voice-search': 'Optimize for voice queries.',
      'vr-staging': 'Showcase properties on pages.',
      'market-reports': 'Offer report as magnet.',
      'agent-collaboration': 'Collaborate on page design.',
      'commission-tracking': 'Track highest commission pages.',
      'social-listening': 'Get copy ideas from social.',
      'chat-integration': 'Add live chat to pages.',
      'contract-management': 'Start contract from page.',
      'showing-feedback': 'Drive users to form.',
      'expense-tracking': 'Track cost vs. revenue.',
      'brand-kit': 'Ensure pages are on-brand.',
      'interactive-maps': 'Embed maps on pages.',
      'event-promotion': 'Create pages for events.',
      'content-calendar': 'Schedule when pages go live.',
      '3d-floor-plans': 'Feature interactive 3D plans.',
    },
  },
  {
    id: 'social-posts',
    title: 'AI Social Post Writer',
    description: "Generate a week's worth of social content from a single link or topic.",
    icon: <Share2 />,
    color: 'from-rose-500/80 to-rose-600/80',
    isIntro: true,
    synergies: {
      'ad-creation': 'Promote campaigns on social.',
      targeting: 'Write posts that resonate.',
      rebranding: 'Generate on-brand content.',
      'landing-pages': 'Drive traffic to pages.',
      'social-posts': "Megaphone: Amplify your message.",
      'lead-gen': 'Use social for traffic.',
      'competitor-analysis': 'See what content works.',
      'market-analysis': 'Create posts about trends.',
      'auto-follow-up': 'Engage commenters automatically.',
      'performance-dashboard': 'Track likes, shares, comments.',
      'email-campaigns': 'Promote channels in newsletters.',
      'crm-integration': 'Capture leads from social.',
      'brochure-rebrand': 'Post rebranded brochures.',
      'offer-management': 'Announce offers on social.',
      'calendar-sync': 'Share availability in posts.',
      'bulk-actions': 'Schedule posts in minutes.',
      'ai-chatbot': 'Auto-respond to DMs.',
      'pdf-ads': 'Share PDFs on LinkedIn.',
      'video-ads': 'Post videos on Reels.',
      'content-syndication': 'Amplify posts across platforms.',
      'client-portal': 'Share performance with clients.',
      'ai-negotiator': 'Gauge interest before negotiating.',
      'pms-integration': 'Announce new rentals.',
      'training-modules': 'Build powerful social presence.',
      'virtual-tours': 'Post tour clips.',
      'roi-calculator': 'Create ROI posts.',
      'listing-management': 'Auto-create "Just Listed" posts.',
      'open-house-scheduler': 'Promote on Facebook events.',
      'closing-assistance': 'Share "Just Sold" posts.',
      'predictive-analytics': 'Predict viral social content.',
      'referral-program': 'Promote program on social.',
      'gamified-sales': 'Run social media contests.',
      'dynamic-pricing': 'Announce flash sales.',
      'a/b-testing': 'Test post formats, captions.',
      'local-seo': 'Use local hashtags, tags.',
      'community-engagement': 'Run polls, quizzes, Q&As.',
      'automated-reporting': 'Get weekly growth reports.',
      'script-generator': 'Generate video script ideas.',
      'drip-campaigns': 'Move leads to funnels.',
      'task-automation': 'Auto-create response tasks.',
      'feedback-surveys': 'Use polls for feedback.',
      'real-time-alerts': 'Alert on brand mentions.',
      'compliance-checker': 'Ensure posts meet guidelines.',
      'document-generator': 'Share helpful guides.',
      'property-websites': 'Promote sites on social.',
      'multi-language': 'Create content for demos.',
      'voice-search': 'Create content for questions.',
      'vr-staging': 'Share before-and-after posts.',
      'market-reports': 'Share insights from reports.',
      'agent-collaboration': 'Amplify each other\'s posts.',
      'commission-tracking': 'Celebrate team successes.',
      'social-listening': 'Find new post ideas.',
      'chat-integration': 'Drive traffic to chat.',
      'contract-management': 'Share tips on contracts.',
      'showing-feedback': 'Post feedback testimonials.',
      'expense-tracking': 'Share marketing investments.',
      'brand-kit': 'Ensure posts are on-brand.',
      'interactive-maps': 'Share location-based data.',
      'event-promotion': 'Drive RSVPs to events.',
      'content-calendar': 'Companion to post writer.',
      '3d-floor-plans': 'Share 3D plan walkthroughs.',
    },
  },
  {
    id: 'lead-gen',
    title: 'AI Lead Generation',
    description: 'Find and qualify high-intent buyers and sellers automatically.',
    icon: <Users />,
    color: 'from-teal-500/80 to-teal-600/80',
    isIntro: true,
    synergies: {
      'ad-creation': 'Capture leads from campaigns.',
      targeting: 'Focus on quality leads.',
      rebranding: 'Strong brand attracts leads.',
      'landing-pages': 'Convert traffic to leads.',
      'social-posts': 'Turn engagement to leads.',
      'lead-gen': 'Magnet: Attract, qualify leads.',
      'competitor-analysis': 'Find competitor-ignored sources.',
      'market-analysis': 'Offer valuable market insights.',
      'auto-follow-up': 'Follow-up begins instantly.',
      'performance-dashboard': 'Track sources, cost, conversions.',
      'email-campaigns': 'Nurture leads with emails.',
      'crm-integration': 'Heart of lead management.',
      'brochure-rebrand': 'Use brochures as magnets.',
      'offer-management': 'Capture interested offer leads.',
      'calendar-sync': 'Let leads book meetings.',
      'bulk-actions': 'Import, process lead lists.',
      'ai-chatbot': '24/7 qualifying machine.',
      'pdf-ads': 'Generate leads from docs.',
      'video-ads': 'Capture leads from video.',
      'content-syndication': 'Generate leads from network.',
      'client-portal': 'Show clients generated leads.',
      'ai-negotiator': 'Qualify on negotiation behavior.',
      'pms-integration': 'Identify sellers from rentals.',
      'training-modules': 'Become a lead expert.',
      'virtual-tours': 'Capture highly engaged leads.',
      'roi-calculator': 'Offer free ROI calculation.',
      'listing-management': 'Every listing a magnet.',
      'open-house-scheduler': 'Capture open house leads.',
      'closing-assistance': 'Generate future satisfied leads.',
      'predictive-analytics': 'Core of modern lead gen.',
      'referral-program': 'Turn network into engine.',
      'gamified-sales': 'Competitions on lead goals.',
      'dynamic-pricing': 'Attract leads with pricing.',
      'a/b-testing': 'Optimize lead capture forms.',
      'local-seo': 'Generate local, organic leads.',
      'community-engagement': 'Build relationships into leads.',
      'automated-reporting': 'Understand your lead flow.',
      'script-generator': 'Equip team for conversion.',
      'drip-campaigns': 'Perfect for lead nurturing.',
      'task-automation': 'Assign new leads.',
      'feedback-surveys': 'Get feedback, improve process.',
      'real-time-alerts': 'Ultimate for speed-to-lead.',
      'compliance-checker': 'Ensure compliant methods.',
      'document-generator': 'Offer docs for info.',
      'property-websites': 'Primary lead capture tool.',
      'multi-language': 'Generate leads from non-natives.',
      'voice-search': 'Capture voice search leads.',
      'vr-staging': 'Offer exclusive staged access.',
      'market-reports': 'Perfect buyer/seller magnet.',
      'agent-collaboration': 'Share leads, collaborate.',
      'commission-tracking': 'See most revenue sources.',
      'social-listening': 'Find leads in conversations.',
      'chat-integration': 'Turn chats to leads.',
      'contract-management': 'Identify leads from contracts.',
      'showing-feedback': 'Identify interested buyers.',
      'expense-tracking': 'Analyze cost-per-lead.',
      'brand-kit': 'Consistent brand builds trust.',
      'interactive-maps': 'Capture leads exploring areas.',
      'event-promotion': 'Generate leads from attendees.',
      'content-calendar': 'Plan campaigns visually.',
      '3d-floor-plans': 'Offer exclusive plan access.',
    },
  },
  {
    id: 'competitor-analysis',
    title: 'Competitor Ad Analysis',
    description: 'See your competitors\' ads, targeting, and messaging.',
    icon: <Binoculars />,
    color: 'from-indigo-500/80 to-indigo-600/80',
    isIntro: true,
    synergies: {
      'ad-creation': 'Create standout ads.',
      targeting: 'Discover untapped audiences.',
      rebranding: 'Position your brand.',
      'landing-pages': 'Build better landing pages.',
      'social-posts': 'Create hijacking social content.',
      'lead-gen': 'Find unknown lead sources.',
      'competitor-analysis': 'Spyglass: See their strategy.',
      'market-analysis': 'Combine data for picture.',
      'auto-follow-up': 'Craft counter-messages.',
      'performance-dashboard': 'Benchmark against competition.',
      'email-campaigns': 'Win the inbox battle.',
      'crm-integration': 'Track competitor lead engagement.',
      'brochure-rebrand': 'Design superior brochures.',
      'offer-management': 'Make unmatched offers.',
      'calendar-sync': 'Offer flexible showing times.',
      'bulk-actions': 'Analyze dozens of competitors.',
      'ai-chatbot': 'Handle competitor questions.',
      'pdf-ads': 'See their shared content.',
      'video-ads': 'Analyze competitor video messaging.',
      'content-syndication': 'See their featured content.',
      'client-portal': 'Show clients your outperformance.',
      'ai-negotiator': 'Gain an edge with pricing.',
      'pms-integration': 'Analyze rental market competition.',
      'training-modules': 'Train on competitive analysis.',
      'virtual-tours': 'Offer better virtual tours.',
      'roi-calculator': 'Show clients better ROI.',
      'listing-management': 'Optimize listings to rank higher.',
      'open-house-scheduler': 'Schedule non-conflicting open houses.',
      'closing-assistance': 'Offer a smoother closing.',
      'predictive-analytics': 'Predict competitor\'s next move.',
      'referral-program': 'Design a better program.',
      'gamified-sales': 'Beat competitor benchmarks.',
      'dynamic-pricing': 'Stay ahead of pricing.',
      'a/b-testing': 'Test against their messaging.',
      'local-seo': 'Outrank for local keywords.',
      'community-engagement': 'Be more visible.',
      'automated-reporting': 'Get weekly activity digests.',
      'script-generator': 'Prepare for competitor objections.',
      'drip-campaigns': 'Highlight your advantages.',
      'task-automation': 'Review competitor activity weekly.',
      'feedback-surveys': 'Ask why you were chosen.',
      'real-time-alerts': 'Alerted on new campaigns.',
      'compliance-checker': 'Check their advertising rules.',
      'document-generator': 'Create value comparison sheets.',
      'property-websites': 'Build more engaging websites.',
      'multi-language': 'See if markets ignored.',
      'voice-search': 'Capture their missed traffic.',
      'vr-staging': 'Offer better virtual staging.',
      'market-reports': 'Provide more insightful reports.',
      'agent-collaboration': 'Team up to beat rivals.',
      'commission-tracking': 'Compare your commission rates.',
      'social-listening': 'Core of competitor analysis.',
      'chat-integration': 'Learn from their live chat.',
      'contract-management': 'Offer more favorable terms.',
      'showing-feedback': 'See buyer feedback on rivals.',
      'expense-tracking': 'Analyze your marketing spend.',
      'brand-kit': 'Develop a contrasting brand.',
      'interactive-maps': 'Provide better local insights.',
      'event-promotion': 'Host more compelling events.',
      'content-calendar': 'Counter their content schedule.',
      '3d-floor-plans': 'Provide more detailed plans.',
    },
  },
  {
    id: 'market-analysis',
    title: 'Real-Time Market Analysis',
    description: 'Access live data on pricing, trends, and inventory.',
    icon: <TrendingUp />,
    color: 'from-cyan-500/80 to-cyan-600/80',
    isIntro: true,
    synergies: {
      'ad-creation': 'Create ads reflecting market.',
      targeting: 'Target trending neighborhood buyers.',
      rebranding: 'Update branding to match market.',
      'landing-pages': 'Incorporate live market stats.',
      'social-posts': 'Post market updates.',
      'lead-gen': 'Offer exclusive market reports.',
      'competitor-analysis': 'See competitor market reactions.',
      'market-analysis': 'Crystal Ball: See trends.',
      'auto-follow-up': 'Send market update emails.',
      'performance-dashboard': 'Correlate performance with market.',
      'email-campaigns': 'Create data-driven campaigns.',
      'crm-integration': 'Enrich contacts with data.',
      'brochure-rebrand': 'Incorporate data into brochures.',
      'offer-management': 'Make offers on comps.',
      'calendar-sync': 'Schedule meetings for trends.',
      'bulk-actions': 'Apply pricing to listings.',
      'ai-chatbot': 'Answer market condition questions.',
      'pdf-ads': 'Include data charts in ads.',
      'video-ads': 'Create videos on trends.',
      'content-syndication': 'Become a market source.',
      'client-portal': 'Give clients personalized view.',
      'ai-negotiator': 'Negotiate with real-time data.',
      'pms-integration': 'Analyze rental market trends.',
      'training-modules': 'Learn to interpret data.',
      'virtual-tours': 'Highlight trending features.',
      'roi-calculator': 'Create accurate ROI projections.',
      'listing-management': 'Price listings on data.',
      'open-house-scheduler': 'Schedule on buyer activity.',
      'closing-assistance': 'Advise clients on closing.',
      'predictive-analytics': 'Forecast market direction.',
      'referral-program': 'Show partners market expertise.',
      'gamified-sales': 'Create quizzes on data.',
      'dynamic-pricing': 'Core engine for pricing.',
      'a/b-testing': 'Test data point conversions.',
      'local-seo': 'Create content on trends.',
      'community-engagement': 'Host Q&As on market.',
      'automated-reporting': 'Send personalized market reports.',
      'script-generator': 'Generate expert-positioning scripts.',
      'drip-campaigns': 'Nurture with trend updates.',
      'task-automation': 'Review key data weekly.',
      'feedback-surveys': 'Ask clients for valuable info.',
      'real-time-alerts': 'Alerted to market shifts.',
      'compliance-checker': 'Ensure clear data visuals.',
      'document-generator': 'Generate CMAs with data.',
      'property-websites': 'Include "Market Trends" section.',
      'multi-language': 'Provide analysis in languages.',
      'voice-search': 'Answer voice search stats.',
      'vr-staging': 'Stage with trending furniture.',
      'market-reports': 'Ultimate for creating reports.',
      'agent-collaboration': 'Share insights with team.',
      'commission-tracking': 'See how trends affect earnings.',
      'social-listening': 'Hear real-time market sentiment.',
      'chat-integration': 'Answer user data questions.',
      'contract-management': 'Draft contracts on conditions.',
      'showing-feedback': 'Correlate feedback with trends.',
      'expense-tracking': 'Invest based on opportunities.',
      'brand-kit': 'Develop data-driven brand.',
      'interactive-maps': 'Visualize trends on map.',
      'event-promotion': 'Host "State of Market" events.',
      'content-calendar': 'Plan around data releases.',
      '3d-floor-plans': 'Highlight in-demand features.',
    },
  },
  {
    id: 'auto-follow-up',
    title: 'Automated Follow-Up',
    description: 'Engage every lead instantly with personalized email and SMS sequences.',
    icon: <Repeat />,
    color: 'from-amber-500/80 to-amber-600/80',
    synergies: {
      'ad-creation': 'Engage leads from ads.',
      targeting: 'Customize for buyer personas.',
      rebranding: 'On-brand automated communications.',
      'landing-pages': 'Trigger sequences from forms.',
      'social-posts': 'Auto-respond to comments, DMs.',
      'lead-gen': 'Convert leads with speed.',
      'competitor-analysis': 'Craft counter-competitor messages.',
      'market-analysis': 'Send automated market updates.',
      'auto-follow-up': 'Autopilot: Nurture leads 24/7.',
      'performance-dashboard': 'Track opens, clicks, replies.',
      'email-campaigns': 'Engine for automated email.',
      'crm-integration': 'Trigger sequences from CRM.',
      'brochure-rebrand': 'Send brochures in sequences.',
      'offer-management': 'Follow up on offers.',
      'calendar-sync': 'Send appointment reminders.',
      'bulk-actions': 'Enroll thousands in sequence.',
      'ai-chatbot': 'Hand off to sequence.',
      'pdf-ads': 'Follow up with downloads.',
      'video-ads': 'Follow up with viewers.',
      'content-syndication': 'Nurture with targeted follow-ups.',
      'client-portal': 'Send automated client updates.',
      'ai-negotiator': 'Automate initial negotiation.',
      'pms-integration': 'Send rent/maintenance reminders.',
      'training-modules': 'Learn effective follow-up copy.',
      'virtual-tours': 'Follow up with viewers.',
      'roi-calculator': 'Send detailed ROI report.',
      'listing-management': 'Send "similar properties" emails.',
      'open-house-scheduler': 'Send reminders and thank yous.',
      'closing-assistance': 'Automate closing communication.',
      'predictive-analytics': 'Send at optimal time.',
      'referral-program': 'Ask for referrals post-closing.',
      'gamified-sales': 'Reward follow-up conversion rates.',
      'dynamic-pricing': 'Notify of price drops.',
      'a/b-testing': 'Test cadence and messaging.',
      'local-seo': 'Follow up with local leads.',
      'community-engagement': 'Welcome new community members.',
      'automated-reporting': 'See sequence performance.',
      'script-generator': 'Generate automated message scripts.',
      'drip-campaigns': 'Foundation of all follow-up.',
      'task-automation': 'Integrate with manual tasks.',
      'feedback-surveys': 'Send surveys after events.',
      'real-time-alerts': 'Trigger sequences by activity.',
      'compliance-checker': 'Ensure compliant messages.',
      'document-generator': 'Send relevant docs automatically.',
      'property-websites': 'Follow up with users.',
      'multi-language': 'Send sequences in language.',
      'voice-search': 'Provide automated answers.',
      'vr-staging': 'Follow up with interested.',
      'market-reports': 'Send reports in sequence.',
      'agent-collaboration': 'Notify team for manual follow-up.',
      'commission-tracking': 'See sequences leading to comms.',
      'social-listening': 'Trigger responses by keywords.',
      'chat-integration': 'Transition to follow-up sequence.',
      'contract-management': 'Send contract deadline reminders.',
      'showing-feedback': 'Request feedback after showing.',
      'expense-tracking': 'Track ROI of systems.',
      'brand-kit': 'Messages reflect your brand.',
      'interactive-maps': 'Follow-ups based on exploration.',
      'event-promotion': 'Send event reminders.',
      'content-calendar': 'Coordinate with content schedule.',
      '3d-floor-plans': 'Follow up based on views.',
    },
  },
  {
    id: 'performance-dashboard',
    title: 'Performance Dashboard',
    description: 'Track every metric, from ad clicks to closed deals, in one place.',
    icon: <Gauge />,
    color: 'from-purple-500/80 to-purple-600/80',
    synergies: {
      'ad-creation': 'See best performing ads.',
      targeting: 'Analyze audience profitability.',
      rebranding: 'Track rebrand impact.',
      'landing-pages': 'Monitor landing page conversions.',
      'social-posts': 'Track social media metrics.',
      'lead-gen': 'View entire lead funnel.',
      'competitor-analysis': 'Benchmark against the competition.',
      'market-analysis': 'Correlate with market trends.',
      'auto-follow-up': 'See best converting sequences.',
      'performance-dashboard': 'Command Center: Business glance.',
      'email-campaigns': 'Track email campaign metrics.',
      'crm-integration': 'Single source of truth.',
      'brochure-rebrand': 'See new brochure engagement.',
      'offer-management': 'Track offer status.',
      'calendar-sync': 'See meeting metrics.',
      'bulk-actions': 'Analyze bulk campaign impact.',
      'ai-chatbot': 'Track chatbot conversations.',
      'pdf-ads': 'Measure PDF ad engagement.',
      'video-ads': 'Track video ad metrics.',
      'content-syndication': 'See best traffic channels.',
      'client-portal': 'Provide clients with dashboard.',
      'ai-negotiator': 'Track negotiation outcomes.',
      'pms-integration': 'Monitor occupancy, rent, KPIs.',
      'training-modules': 'Track team training progress.',
      'virtual-tours': 'Analyze virtual tour engagement.',
      'roi-calculator': 'Compare projected vs actual.',
      'listing-management': 'See most viewed listings.',
      'open-house-scheduler': 'Track open house metrics.',
      'closing-assistance': 'Monitor time-to-close.',
      'predictive-analytics': 'See prediction accuracy.',
      'referral-program': 'Track referral revenue.',
      'gamified-sales': 'Dashboard is the scoreboard.',
      'dynamic-pricing': 'See pricing adjustment impact.',
      'a/b-testing': 'See A/B test results.',
      'local-seo': 'Track SEO rankings, traffic.',
      'community-engagement': 'Measure community metrics.',
      'automated-reporting': 'Engine for automated reports.',
      'script-generator': 'See best converting scripts.',
      'drip-campaigns': 'Analyze long-term performance.',
      'task-automation': 'Track task completion rates.',
      'feedback-surveys': 'Visualize feedback data trends.',
      'real-time-alerts': 'See live activity feed.',
      'compliance-checker': 'Dashboard for compliance activities.',
      'document-generator': 'Track document generation.',
      'property-websites': 'Monitor website metrics.',
      'multi-language': 'See most engaging languages.',
      'voice-search': 'Track voice query volume.',
      'vr-staging': 'See if staging sells faster.',
      'market-reports': 'Track market report downloads.',
      'agent-collaboration': 'Central team performance dash.',
      'commission-tracking': 'Ultimate earnings tracking.',
      'social-listening': 'Dashboard of social sentiment.',
      'chat-integration': 'Analyze chat metrics.',
      'contract-management': 'Track all contract statuses.',
      'showing-feedback': 'Visualize showing feedback.',
      'expense-tracking': 'Financial business dashboard.',
      'brand-kit': 'Track brand asset usage.',
      'interactive-maps': 'See most clicked map areas.',
      'event-promotion': 'Track event metrics.',
      'content-calendar': 'View all marketing activities.',
      '3d-floor-plans': 'Track 3D floor plan engagement.',
    },
  },
  {
    id: 'email-campaigns',
    title: 'AI Email Campaigns',
    description: 'Create and automate beautiful, high-converting email blasts.',
    icon: <Mail />,
    color: 'from-lime-500/80 to-lime-600/80',
    synergies: {
      'ad-creation': 'Use ad visuals in emails.',
      targeting: 'Segment lists with precision.',
      rebranding: 'Create on-brand templates.',
      'landing-pages': 'Drive traffic to pages.',
      'social-posts': 'Promote channels in newsletters.',
      'lead-gen': 'Nurture leads into clients.',
      'competitor-analysis': 'Write better subject lines.',
      'market-analysis': 'Send data-driven updates.',
      'auto-follow-up': 'Engine for automated emails.',
      'performance-dashboard': 'Track opens, clicks, conversions.',
      'email-campaigns': 'Inbox Infiltrator: Get clicks.',
      'crm-integration': 'Sync lists with CRM.',
      'brochure-rebrand': 'Send brochures via email.',
      'offer-management': 'Email offers to buyers.',
      'calendar-sync': 'Embed calendar link.',
      'bulk-actions': 'Send campaigns to thousands.',
      'ai-chatbot': 'Capture subscribers via chat.',
      'pdf-ads': 'Distribute PDFs to list.',
      'video-ads': 'Embed videos in emails.',
      'content-syndication': 'Promote content in newsletters.',
      'client-portal': 'Send email updates to clients.',
      'ai-negotiator': 'Conduct negotiations over email.',
      'pms-integration': 'Send newsletters to tenants.',
      'training-modules': 'Learn compelling email copy.',
      'virtual-tours': 'Email tours to hot leads.',
      'roi-calculator': 'Send ROI calcs to leads.',
      'listing-management': 'Send "Just Listed" emails.',
      'open-house-scheduler': 'Email open house invitations.',
      'closing-assistance': 'Keep clients informed via email.',
      'predictive-analytics': 'Send emails at optimal time.',
      'referral-program': 'Email past clients for referrals.',
      'gamified-sales': 'Contests on email engagement.',
      'dynamic-pricing': 'Email price drop alerts.',
      'a/b-testing': 'Test subject lines, content.',
      'local-seo': 'Build list via website.',
      'community-engagement': 'Send newsletters to community.',
      'automated-reporting': 'Get reports on performance.',
      'script-generator': 'Generate subject lines, copy.',
      'drip-campaigns': 'Foundation of email marketing.',
      'task-automation': 'Create tasks on interactions.',
      'feedback-surveys': 'Email surveys for feedback.',
      'real-time-alerts': 'Get alert on hot lead open.',
      'compliance-checker': 'Ensure CAN-SPAM compliance.',
      'document-generator': 'Email docs for e-signature.',
      'property-websites': 'Drive traffic to websites.',
      'multi-language': 'Send campaigns in languages.',
      'voice-search': 'Email content answering questions.',
      'vr-staging': 'Email staged photos.',
      'market-reports': 'Use reports as lead magnet.',
      'agent-collaboration': 'Share templates with team.',
      'commission-tracking': 'Track which campaigns earn.',
      'social-listening': 'Get content ideas from social.',
      'chat-integration': 'Continue chat via email.',
      'contract-management': 'Email contracts for review.',
      'showing-feedback': 'Email feedback requests.',
      'expense-tracking': 'Track ROI of email efforts.',
      'brand-kit': 'Ensure every email on-brand.',
      'interactive-maps': 'Send maps of properties.',
      'event-promotion': 'Primary tool for events.',
      'content-calendar': 'Schedule campaigns with content.',
      '3d-floor-plans': 'Email interactive floor plans.',
    },
  },
  {
    id: 'crm-integration',
    title: 'Seamless CRM Integration',
    description: 'Sync all your data with the CRM you already use.',
    icon: <Network />,
    color: 'from-red-500/80 to-red-600/80',
    synergies: {
      'ad-creation': 'Pipe leads to CRM.',
      targeting: 'Enrich CRM with data.',
      rebranding: 'Brand consistency across platforms.',
      'landing-pages': 'Leads flow into CRM.',
      'social-posts': 'Capture leads to CRM.',
      'lead-gen': 'Heart of lead management.',
      'competitor-analysis': 'Track competitor lead engagement.',
      'market-analysis': 'Enrich contact with data.',
      'auto-follow-up': 'Trigger CRM workflows.',
      'performance-dashboard': 'Unify data for 360 view.',
      'email-campaigns': 'Sync lists, data with CRM.',
      'crm-integration': 'Central Nervous System.',
      'brochure-rebrand': 'Log brochure sends in CRM.',
      'offer-management': 'Manage offers in CRM.',
      'calendar-sync': 'Sync meetings with CRM.',
      'bulk-actions': 'Update thousands of records.',
      'ai-chatbot': 'Save chats, leads to CRM.',
      'pdf-ads': 'Log PDF views in CRM.',
      'video-ads': 'Track video engagement.',
      'content-syndication': 'Attribute leads in CRM.',
      'client-portal': 'Sync client activity in CRM.',
      'ai-negotiator': 'Log negotiation in CRM.',
      'pms-integration': 'Bi-directional PMS/CRM sync.',
      'training-modules': 'Track training in CRM.',
      'virtual-tours': 'See who viewed tours.',
      'roi-calculator': 'Save ROI calcs to CRM.',
      'listing-management': 'Associate contacts with listings.',
      'open-house-scheduler': 'Add attendees to CRM.',
      'closing-assistance': 'Manage checklist in CRM.',
      'predictive-analytics': 'Use CRM for predictions.',
      'referral-program': 'Track referrals in CRM.',
      'gamified-sales': 'Pull CRM for leaderboards.',
      'dynamic-pricing': 'Log pricing in deal records.',
      'a/b-testing': 'Log tests results in CRM.',
      'local-seo': 'Attribute SEO leads in CRM.',
      'community-engagement': 'Add members to CRM.',
      'automated-reporting': 'Generate reports from CRM.',
      'script-generator': 'Save scripts to contacts.',
      'drip-campaigns': 'Trigger drips by status.',
      'task-automation': 'Create, manage tasks in CRM.',
      'feedback-surveys': 'Save surveys to contacts.',
      'real-time-alerts': 'Trigger alerts by data.',
      'compliance-checker': 'Log consent in CRM.',
      'document-generator': 'Generate docs from CRM.',
      'property-websites': 'Log website activity in CRM.',
      'multi-language': 'Store language pref in CRM.',
      'voice-search': 'Log voice queries in CRM.',
      'vr-staging': 'Note who viewed staging.',
      'market-reports': 'Log downloads in CRM.',
      'agent-collaboration': 'Collaborate on CRM records.',
      'commission-tracking': 'Automate commission calcs.',
      'social-listening': 'Create contacts from social.',
      'chat-integration': 'Save chats to CRM.',
      'contract-management': 'Manage contracts in CRM.',
      'showing-feedback': 'Log feedback on records.',
      'expense-tracking': 'Associate expenses with deals.',
      'brand-kit': 'Maintain data consistency.',
      'interactive-maps': 'Log interest areas in CRM.',
      'event-promotion': 'Track attendance in CRM.',
      'content-calendar': 'Base content on CRM data.',
      '3d-floor-plans': 'See who viewed plans.',
    },
  },
  {
    id: 'brochure-rebrand',
    title: 'Brochure Rebranding',
    description: 'Upload any project brochure. Our AI instantly rebrands it.',
    icon: <FilePlus />,
    color: 'from-emerald-500/80 to-emerald-600/80',
    synergies: {
      'ad-creation': 'Use brochures in ads.',
      targeting: 'Create versions for audiences.',
      rebranding: 'Core of automated rebranding.',
      'landing-pages': 'Offer brochures as download.',
      'social-posts': 'Share brochures on social.',
      'lead-gen': 'Use brochures as magnets.',
      'competitor-analysis': 'Create better-looking brochures.',
      'market-analysis': 'Incorporate data into brochures.',
      'auto-follow-up': 'Send brochures in sequences.',
      'performance-dashboard': 'Track downloads and views.',
      'email-campaigns': 'Attach brochures to emails.',
      'crm-integration': 'Log sends, views in CRM.',
      'brochure-rebrand': 'Alchemist: Turn brochure to gold.',
      'offer-management': 'Include link with offers.',
      'calendar-sync': 'Send brochure before meeting.',
      'bulk-actions': 'Rebrand, distribute all listings.',
      'ai-chatbot': 'Chatbot can send brochures.',
      'pdf-ads': 'Use brochures as PDF ads.',
      'video-ads': 'Create videos of brochures.',
      'content-syndication': 'Syndicate brochures on platforms.',
      'client-portal': 'Give clients access to brochures.',
      'ai-negotiator': 'Use brochure in negotiations.',
      'pms-integration': 'Create brochures for rentals.',
      'training-modules': 'Learn design to enhance.',
      'virtual-tours': 'Link to tour from brochure.',
      'roi-calculator': 'Include ROI in brochures.',
      'listing-management': 'A brochure for every listing.',
      'open-house-scheduler': 'Have copies at open houses.',
      'closing-assistance': 'Provide branded closing package.',
      'predictive-analytics': 'Analyze best engaging designs.',
      'referral-program': 'Create referral program brochure.',
      'gamified-sales': 'Challenge team to create best.',
      'dynamic-pricing': 'Update pricing in brochures.',
      'a/b-testing': 'Test different brochure versions.',
      'local-seo': 'Make brochures discoverable.',
      'community-engagement': 'Create brochures for events.',
      'automated-reporting': 'Track brochure performance.',
      'script-generator': 'Generate compelling copy.',
      'drip-campaigns': 'Use in drip campaigns.',
      'task-automation': 'Create follow-up task.',
      'feedback-surveys': 'Get feedback on designs.',
      'real-time-alerts': 'Alert on brochure download.',
      'compliance-checker': 'Ensure brochures have legal text.',
      'document-generator': 'Foundation for other docs.',
      'property-websites': 'Offer downloads on websites.',
      'multi-language': 'Rebrand brochures in languages.',
      'voice-search': 'Make content voice accessible.',
      'vr-staging': 'Include staged photos.',
      'market-reports': 'Create branded summary report.',
      'agent-collaboration': 'Collaborate on brochure design.',
      'commission-tracking': 'See which brochures earn.',
      'social-listening': 'Get content ideas from social.',
      'chat-integration': 'Offer brochure during chat.',
      'contract-management': 'Consistent branding to contract.',
      'showing-feedback': 'Send thank-you with brochure.',
      'expense-tracking': 'Track cost and ROI.',
      'brand-kit': 'Engine for one-click rebrand.',
      'interactive-maps': 'Embed QR codes in brochures.',
      'event-promotion': 'Distribute brochures at events.',
      'content-calendar': 'Schedule brochure release.',
      '3d-floor-plans': 'Include stunning 3D plans.',
    },
  },
  {
    id: 'offer-management',
    title: 'Offer Management Portal',
    description: 'Receive, counter, and accept offers in one streamlined portal.',
    icon: <Handshake />,
    color: 'from-yellow-500/80 to-yellow-600/80',
    synergies: {
      'ad-creation': 'Drive ad traffic.',
      'offer-management': 'Deal Table: Manage offers.',
    },
  },
  {
    id: 'calendar-sync',
    title: 'Smart Calendar Sync',
    description: 'Sync your schedule and let qualified leads book meetings.',
    icon: <Calendar />,
    color: 'from-violet-500/80 to-violet-600/80',
    synergies: {
      'ad-creation': 'Leads book meetings directly.',
      'calendar-sync': 'Time Saver: Automate schedule.',
    },
  },
  {
    id: 'bulk-actions',
    title: 'Bulk Campaign Actions',
    description: 'Launch ads, emails, and updates across all listings at once.',
    icon: <ClipboardList />,
    color: 'from-stone-500/80 to-stone-600/80',
    synergies: {
      'ad-creation': 'Launch a dozen variations.',
      'bulk-actions': 'Multiplier: Act in minutes.',
    },
  },
  {
    id: 'ai-chatbot',
    title: '24/7 AI Chatbot',
    description: 'Engage and qualify website visitors, even when you\'re asleep.',
    icon: <Bot />,
    color: 'from-sky-500/80 to-sky-600/80',
    synergies: {
      'ad-creation': 'Qualify ad leads 24/7.',
      'ai-chatbot': 'Night Owl: Never sleeps.',
    },
  },
  {
    id: 'pdf-ads',
    title: 'Interactive PDF Ads',
    description: 'Convert static PDFs into engaging, trackable lead magnets.',
    icon: <FileText />,
    color: 'from-fuchsia-500/80 to-fuchsia-600/80',
    synergies: {
      'ad-creation': 'Convert PDFs to ads.',
      'pdf-ads': 'Document Dynamo: Turn PDF to lead machine.',
    },
  },
  {
    id: 'video-ads',
    title: 'AI Video Ad Generator',
    description: 'Create compelling short-form video ads from photos and text.',
    icon: <Video />,
    color: 'from-orange-400/80 to-orange-500/80',
    synergies: {
      'ad-creation': 'Generate compelling video ads.',
      'video-ads': 'Director: Create video ads.',
    },
  },
  {
    id: 'content-syndication',
    title: 'Content Syndication',
    description: 'Automatically push your listings and content to partner sites.',
    icon: <Network />,
    color: 'from-green-400/80 to-green-500/80',
    synergies: {
      'ad-creation': 'Push content across platforms.',
      'content-syndication': 'Amplifier: Get seen everywhere.',
    },
  },
  {
    id: 'client-portal',
    title: 'White-Label Client Portal',
    description: 'Give clients a branded, real-time view of their campaign performance.',
    icon: <Briefcase />,
    color: 'from-blue-400/80 to-blue-500/80',
    synergies: {
      'ad-creation': 'Give clients real-time view.',
      'client-portal': 'VIP Room: Branded experience.',
    },
  },
  {
    id: 'ai-negotiator',
    title: 'AI-Powered Negotiator',
    description: 'Let our AI handle initial offers and counter-offers for you.',
    icon: <BrainCircuit />,
    color: 'from-pink-400/80 to-pink-500/80',
    synergies: {
      'ad-creation': 'AI handles initial offers.',
      'ai-negotiator': 'Closer: AI handles negotiation.',
    },
  },
  {
    id: 'pms-integration',
    title: 'PMS Integration',
    description: 'Sync with your property management software for seamless data flow.',
    icon: <Building />,
    color: 'from-teal-400/80 to-teal-500/80',
    synergies: {
      'ad-creation': 'Sync ad campaigns with PMS.',
      'pms-integration': 'Bridge: Connect sales and data.',
    },
  },
  {
    id: 'training-modules',
    title: 'Agent Training Modules',
    description: 'Access a library of AI-powered training to sharpen your skills.',
    icon: <BookOpen />,
    color: 'from-indigo-400/80 to-indigo-500/80',
    synergies: {
      'ad-creation': 'Learn high-converting ad copy.',
      'training-modules': 'Dojo: Sharpen your skills.',
    },
  },
  {
    id: 'virtual-tours',
    title: 'Immersive Virtual Tours',
    description: 'Create and embed stunning 3D tours that captivate buyers.',
    icon: <Camera />,
    color: 'from-rose-400/80 to-rose-500/80',
    synergies: {
      'ad-creation': 'Embed 3D tours in ads.',
      'virtual-tours': 'Holodeck: Walk through home.',
    },
  },
  {
    id: 'roi-calculator',
    title: 'ROI Calculator',
    description: 'Project and prove the value of an investment property.',
    icon: <DollarSign />,
    color: 'from-lime-400/80 to-lime-600/80',
    synergies: {
      'ad-creation': 'Project ad campaign return.',
      'roi-calculator': 'Oracle: Prove investment value.',
    },
  },
  {
    id: 'listing-management',
    title: 'Centralized Listing Management',
    description: 'Manage all your listings across all platforms from one place.',
    icon: <ClipboardCheck />,
    color: 'from-amber-400/80 to-amber-500/80',
    synergies: {
      'ad-creation': 'Create ads for listings.',
      'listing-management': 'Master Key: Manage listings.',
    },
  },
  {
    id: 'open-house-scheduler',
    title: 'Open House Scheduler',
    description: 'Plan, promote, and manage open house attendance.',
    icon: <CalendarCheck />,
    color: 'from-purple-400/80 to-purple-500/80',
    synergies: {
      'ad-creation': 'Funnel traffic to sign-ups.',
      'open-house-scheduler': 'Host: Plan flawless open houses.',
    },
  },
  {
    id: 'closing-assistance',
    title: 'AI Closing Assistant',
    description: 'Automate document collection and deadline reminders for smooth closings.',
    icon: <Key />,
    color: 'from-cyan-400/80 to-cyan-500/80',
    synergies: {
      'ad-creation': 'Generate docs from leads.',
      'closing-assistance': 'Concierge: Ensure smooth closing.',
    },
  },
  {
    id: 'predictive-analytics',
    title: 'Predictive Analytics',
    description: 'Our AI predicts which leads will convert and which houses will sell.',
    icon: <Lightbulb />,
    color: 'from-red-400/80 to-red-500/80',
    synergies: {
      'ad-creation': 'Anticipate best creative.',
      'predictive-analytics': 'Fortune Teller: Predict leads.',
    },
  },
  {
    id: 'referral-program',
    title: 'Automated Referral Program',
    description: 'Turn your happy clients into a powerful referral engine.',
    icon: <Users />,
    color: 'from-emerald-400/80 to-emerald-500/80',
    synergies: {
      'ad-creation': 'Build referral campaigns.',
      'referral-program': 'Networker: Clients are sales force.',
    },
  },
  {
    id: 'gamified-sales',
    title: 'Gamified Sales Contests',
    description: 'Boost team motivation with leaderboards, badges, and rewards.',
    icon: <Award />,
    color: 'from-yellow-400/80 to-yellow-500/80',
    synergies: {
      'ad-creation': 'Drive friendly competition.',
      'gamified-sales': 'Arena: Turn sales into sport.',
    },
  },
  {
    id: 'dynamic-pricing',
    title: 'Dynamic Pricing Suggestions',
    description: 'Use AI to recommend the optimal price based on market data.',
    icon: <Sparkles />,
    color: 'from-violet-400/80 to-violet-500/80',
    synergies: {
      'ad-creation': 'Adjust ad offers.',
      'dynamic-pricing': 'Price is Right: Know price.',
    },
  },
  {
    id: 'a/b-testing',
    title: 'A/B Testing Engine',
    description: 'Test everything from ad copy to email subject lines to find what works.',
    icon: <Filter />,
    color: 'from-stone-400/80 to-stone-500/80',
    synergies: {
      'ad-creation': 'Test ad versions.',
      'a/b-testing': 'Scientist: Find what works.',
    },
  },
  {
    id: 'local-seo',
    title: 'Local SEO Booster',
    description: 'Dominate local search results and be the go-to agent in your area.',
    icon: <MapPin />,
    color: 'from-sky-400/80 to-sky-500/80',
    synergies: {
      'ad-creation': 'Boost ad visibility.',
      'local-seo': 'Mayor: Become #1 agent.',
    },
  },
  {
    id: 'community-engagement',
    title: 'Community Engagement Tools',
    description: 'Build and manage your online community with AI-powered tools.',
    icon: <Headset />,
    color: 'from-fuchsia-400/80 to-fuchsia-500/80',
    synergies: {
      'ad-creation': 'Target community groups.',
      'community-engagement': 'Town Square: Build community.',
    },
  },
  {
    id: 'automated-reporting',
    title: 'Automated Client Reporting',
    description: 'Send beautiful, automated performance reports to your clients.',
    icon: <BarChart />,
    color: 'from-orange-300/80 to-orange-400/80',
    synergies: {
      'ad-creation': 'Send automated ad reports.',
      'automated-reporting': 'Analyst: Deliver stunning reports.',
    },
  },
  {
    id: 'script-generator',
    title: 'AI Script Generator',
    description: 'Generate scripts for cold calls, video ads, and follow-up messages.',
    icon: <PenTool />,
    color: 'from-green-300/80 to-green-400/80',
    synergies: {
      'ad-creation': 'Generate video ad scripts.',
      'script-generator': 'Playwright: Never be wordless.',
    },
  },
  {
    id: 'drip-campaigns',
    title: 'Long-Term Drip Campaigns',
    description: 'Nurture leads for months or even years with automated campaigns.',
    icon: <Mails />,
    color: 'from-blue-300/80 to-blue-400/80',
    synergies: {
      'ad-creation': 'Nurture ad leads long-term.',
      'drip-campaigns': 'Gardener: Nurture ready leads.',
    },
  },
  {
    id: 'task-automation',
    title: 'Task Automation',
    description: 'Automate your to-do list and focus on what matters most.',
    icon: <ClipboardList />,
    color: 'from-pink-300/80 to-pink-400/80',
    synergies: {
      'ad-creation': 'Create new lead tasks.',
      'task-automation': 'Butler: AI handles busywork.',
    },
  },
  {
    id: 'feedback-surveys',
    title: 'Automated Feedback Surveys',
    description: 'Collect valuable feedback from clients and leads automatically.',
    icon: <MessageCircle />,
    color: 'from-teal-300/80 to-teal-400/80',
    synergies: {
      'ad-creation': 'Survey ad respondents.',
      'feedback-surveys': 'Listener: Gather feedback.',
    },
  },
  {
    id: 'real-time-alerts',
    title: 'Real-Time Activity Alerts',
    description: 'Get instant notifications for hot lead activity on your site.',
    icon: <Zap />,
    color: 'from-indigo-300/80 to-indigo-400/80',
    synergies: {
      'ad-creation': 'Instant new lead notifications.',
      'real-time-alerts': 'Watchtower: Never miss opportunity.',
    },
  },
  {
    id: 'compliance-checker',
    title: 'Compliance Checker',
    description: 'Ensure your marketing materials meet all regulatory standards.',
    icon: <ShieldCheck />,
    color: 'from-rose-300/80 to-rose-400/80',
    synergies: {
      'ad-creation': 'Ensure ads meet standards.',
      'compliance-checker': 'Guardian: Stay safe, compliant.',
    },
  },
  {
    id: 'document-generator',
    title: 'Document Generator',
    description: 'Automatically generate contracts, CMAs, and other documents.',
    icon: <FileUp />,
    color: 'from-lime-300/80 to-lime-400/80',
    synergies: {
      'ad-creation': 'Generate contracts from leads.',
      'document-generator': 'Scribe: Generate all docs.',
    },
  },
  {
    id: 'property-websites',
    title: 'Single Property Websites',
    description: 'Create a stunning, dedicated website for each listing in minutes.',
    icon: <LayoutTemplate />,
    color: 'from-amber-300/80 to-amber-400/80',
    synergies: {
      'ad-creation': 'Create a unique website.',
      'property-websites': 'Architect: Build stunning website.',
    },
  },
  {
    id: 'multi-language',
    title: 'Multi-Language Support',
    description: 'Translate your marketing materials into multiple languages.',
    icon: <MessageCircle />,
    color: 'from-purple-300/80 to-purple-400/80',
    synergies: {
      'ad-creation': 'Generate ads in many languages.',
      'multi-language': 'Translator: Speak client\'s language.',
    },
  },
  {
    id: 'voice-search',
    title: 'Voice Search Optimization',
    description: 'Optimize your content to be found via voice assistants.',
    icon: <Headset />,
    color: 'from-cyan-300/80 to-cyan-400/80',
    synergies: {
      'ad-creation': 'Optimize for voice queries.',
      'voice-search': 'Herald: Be the answer.',
    },
  },
  {
    id: 'vr-staging',
    title: 'Virtual Reality Staging',
    description: 'Stage properties virtually to help buyers visualize their new home.',
    icon: <Gem />,
    color: 'from-red-300/80 to-red-400/80',
    synergies: {
      'ad-creation': 'Use virtually staged photos.',
      'vr-staging': 'Dream Weaver: Stage any home.',
    },
  },
  {
    id: 'market-reports',
    title: 'Hyper-Local Market Reports',
    description: 'Generate beautiful, data-rich reports for any neighborhood.',
    icon: <FileSearch />,
    color: 'from-emerald-300/80 to-emerald-400/80',
    synergies: {
      'ad-creation': 'Incorporate hyper-local data.',
      'market-reports': 'Town Crier: Generate reports.',
    },
  },
  {
    id: 'agent-collaboration',
    title: 'Team Collaboration Tools',
    description: 'Collaborate with your team on listings, leads, and campaigns.',
    icon: <Users />,
    color: 'from-yellow-300/80 to-yellow-400/80',
    synergies: {
      'ad-creation': 'Collaborate on ad campaigns.',
      'agent-collaboration': 'Round Table: Achieve more.',
    },
  },
  {
    id: 'commission-tracking',
    title: 'Commission Tracking',
    description: 'Track your commissions and get projections for future earnings.',
    icon: <LineChart />,
    color: 'from-violet-300/80 to-violet-400/80',
    synergies: {
      'ad-creation': 'Track ad-generated commissions.',
      'commission-tracking': 'Treasurer: Watch earnings grow.',
    },
  },
  {
    id: 'social-listening',
    title: 'Social Media Listening',
    description: 'Track mentions of your brand and identify potential leads.',
    icon: <Binoculars />,
    color: 'from-stone-300/80 to-stone-400/80',
    synergies: {
      'ad-creation': 'Discover new ad angles.',
      'social-listening': 'Ear: Hear hidden opportunities.',
    },
  },
  {
    id: 'chat-integration',
    title: 'Live Chat Integration',
    description: 'Add live chat to your website and talk to visitors in real-time.',
    icon: <MessageCircle />,
    color: 'from-sky-300/80 to-sky-400/80',
    synergies: {
      'ad-creation': 'Engage leads via chat.',
      'chat-integration': 'Concierge Desk: Be there.',
    },
  },
  {
    id: 'contract-management',
    title: 'Contract Management',
    description: 'Manage the entire lifecycle of your contracts, from draft to signature.',
    icon: <FileText />,
    color: 'from-fuchsia-300/80 to-fuchsia-400/80',
    synergies: {
      'ad-creation': 'Manage contracts from leads.',
      'contract-management': 'Dealmaker: Streamline contracts.',
    },
  },
  {
    id: 'showing-feedback',
    title: 'Automated Showing Feedback',
    description: 'Automatically request and collect feedback after every showing.',
    icon: <ClipboardCheck />,
    color: 'from-orange-200/80 to-orange-300/80',
    synergies: {
      'ad-creation': 'Collect feedback from showings.',
      'showing-feedback': 'Critic: Get honest feedback.',
    },
  },
  {
    id: 'expense-tracking',
    title: 'Expense Tracking',
    description: 'Track all your business expenses and see where your money is going.',
    icon: <DollarSign />,
    color: 'from-green-200/80 to-green-300/80',
    synergies: {
      'ad-creation': 'Track all ad spend.',
      'expense-tracking': 'Accountant: Keep finances in order.',
    },
  },
  {
    id: 'brand-kit',
    title: 'Centralized Brand Kit',
    description: 'Store your logos, colors, and fonts for easy access.',
    icon: <Briefcase />,
    color: 'from-blue-200/80 to-blue-300/80',
    synergies: {
      'ad-creation': 'Ensure ads are on-brand.',
      'brand-kit': 'Style Guide: Ensure consistency.',
    },
  },
  {
    id: 'interactive-maps',
    title: 'Interactive Property Maps',
    description: 'Create beautiful, interactive maps of your listings.',
    icon: <MapPin />,
    color: 'from-pink-200/80 to-pink-300/80',
    synergies: {
      'ad-creation': 'Include maps in pages.',
      'interactive-maps': 'Cartographer: Bring listings to life.',
    },
  },
  {
    id: 'event-promotion',
    title: 'Event Promotion Tools',
    description: 'Promote your open houses, webinars, and other events.',
    icon: <Megaphone />,
    color: 'from-teal-200/80 to-teal-300/80',
    synergies: {
      'ad-creation': 'Promote events with ads.',
      'event-promotion': 'Party Planner: Pack events.',
    },
  },
  {
    id: 'content-calendar',
    title: 'Content Calendar',
    description: 'Plan and schedule all your content in one visual calendar.',
    icon: <Calendar />,
    color: 'from-indigo-200/80 to-indigo-300/80',
    synergies: {
      'ad-creation': 'Schedule ad campaigns visually.',
      'content-calendar': 'Strategist: Plan your marketing.',
    },
  },
  {
    id: '3d-floor-plans',
    title: '3D Floor Plan Generator',
    description: 'Turn standard floor plans into immersive 3D models.',
    icon: <Gem />,
    color: 'from-rose-200/80 to-rose-300/80',
    synergies: {
      'ad-creation': 'Showcase with 3D plans.',
      '3d-floor-plans': 'Dollhouse: Explore in 3D.',
    },
  },
];

const INTRO_CARD_COUNT = 8;

const FeatureCard = ({
  feature,
  index,
  hoveredId,
  setHoveredId,
  onClick,
}: {
  feature: (typeof features)[0];
  index: number;
  hoveredId: string | null;
  setHoveredId: (id: string | null) => void;
  onClick: (id: string) => void;
}) => {
  const isHovered = hoveredId === feature.id;

  return (
    <div
      className={cn(
        "group relative flex flex-col [perspective:1000px] animate-fade-in-up transition-all duration-300",
        isHovered ? 'scale-105 z-10' : 'hover:scale-105',
      )}
      style={{ animationDelay: `${index * 20}ms` }}
      onMouseEnter={() => setHoveredId(feature.id)}
      onClick={() => onClick(feature.id)}
    >
      <div
        className={cn(
          'relative w-full h-[420px] text-white rounded-3xl',
          'transition-transform duration-700 ease-in-out [transform-style:preserve-3d]',
           isHovered ? '[transform:rotateY(180deg)]' : ''
        )}
      >
        {/* Front of the card */}
        <div
          className={cn(
            'absolute inset-0 flex flex-col justify-between p-8 bg-gradient-to-br rounded-3xl',
            'transition-opacity duration-500',
            feature.color,
            '[backface-visibility:hidden]',
          )}
        >
            <div className="z-10 flex flex-col h-full">
              <div className="mb-4 p-3 bg-white/20 rounded-full w-fit">
                {React.cloneElement(feature.icon, { className: 'h-8 w-8' })}
              </div>
              <h2 className="text-3xl font-bold mb-3">{feature.title}</h2>
              <p className="text-lg opacity-90 flex-grow">{feature.description}</p>
              <Button
                size="lg"
                variant="ghost"
                className='bg-white/10 hover:bg-white/20 text-white w-full backdrop-blur-sm border border-white/20 mt-auto'
              >
                Learn more
                <ArrowRight className="ml-2 transition-transform duration-300 group-hover:translate-x-1" />
              </Button>
            </div>
        </div>

        {/* Back of the card - Active State */}
        <div
          className={cn(
            'absolute inset-0 flex flex-col items-center justify-center p-8 bg-gradient-to-br rounded-3xl',
            feature.color,
            '[backface-visibility:hidden] [transform:rotateY(180deg)]'
          )}
        >
            <h3 className="text-4xl font-bold text-center drop-shadow-lg">
              { (feature.synergies as any)[feature.id] || "Unlock Potential"}
            </h3>
        </div>
      </div>
    </div>
  );
};


export default function Home() {
  const { toast } = useToast();
  const [hoveredId, setHoveredId] = React.useState<string | null>(null);
  const [clickedCards, setClickedCards] = React.useState<Set<string>>(new Set());
  const [showConfetti, setShowConfetti] = React.useState(false);

  const handleCardClick = (id: string) => {
    const newClicked = new Set(clickedCards);
    newClicked.add(id);
    setClickedCards(newClicked);

    if (newClicked.size === 1) {
      toast({
        title: "Great start! ✨",
        description: "Click two more cards to see the magic.",
      });
    } else if (newClicked.size === 3) {
      toast({
        title: "Awesome! You're getting it. 🚀",
        description: "The possibilities are endless.",
      });
      setShowConfetti(true);
    }
  };

  return (
    <div className="flex min-h-screen flex-col bg-background">
      {showConfetti && <Confetti />}
      <LandingHeader />
      <main className="flex-1 w-full max-w-full px-4 md:px-6 lg:px-8 py-12 md:py-20">
        <div className="text-center mb-16 max-w-5xl mx-auto">
          <h1 className="text-4xl md:text-7xl font-bold tracking-tighter mb-4 bg-clip-text text-transparent bg-gradient-to-b from-foreground/90 to-foreground/60">
            A salesperson with tools is a super-seller.
          </h1>
          <p className="text-lg md:text-xl text-foreground/60">
            A salesperson without tools is just looking for help. Explore the tools below.
          </p>
        </div>

        <div 
            className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5 gap-8 lg:gap-12 max-w-[120rem] mx-auto"
            onMouseLeave={() => setHoveredId(null)}
        >
          {features.map((feature, index) => (
            <FeatureCard 
                key={feature.id} 
                feature={feature} 
                index={index} 
                hoveredId={hoveredId}
                setHoveredId={setHoveredId}
                onClick={handleCardClick}
            />
          ))}
        </div>
      </main>
      <LandingFooter />
    </div>
  );
}

    